// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: api/msg/msg.proto

package msg

import (
	constant "github.com/xiaohuashifu/him/api/constant"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 图片类型
type Image_Format int32

const (
	Image_FORMAT_UNSPECIFIED Image_Format = 0 // 未知
	Image_FORMAT_JPG         Image_Format = 1 // JPG格式
	Image_FORMAT_PNG         Image_Format = 2 // PNG格式
)

// Enum value maps for Image_Format.
var (
	Image_Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_JPG",
		2: "FORMAT_PNG",
	}
	Image_Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_JPG":         1,
		"FORMAT_PNG":         2,
	}
)

func (x Image_Format) Enum() *Image_Format {
	p := new(Image_Format)
	*p = x
	return p
}

func (x Image_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Image_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_msg_msg_proto_enumTypes[0].Descriptor()
}

func (Image_Format) Type() protoreflect.EnumType {
	return &file_api_msg_msg_proto_enumTypes[0]
}

func (x Image_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Image_Format.Descriptor instead.
func (Image_Format) EnumDescriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{0, 0}
}

// 语音类型
type Voice_Format int32

const (
	Voice_FORMAT_UNSPECIFIED Voice_Format = 0 // 未知
	Voice_FORMAT_MP3         Voice_Format = 1 // MP3格式
)

// Enum value maps for Voice_Format.
var (
	Voice_Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_MP3",
	}
	Voice_Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_MP3":         1,
	}
)

func (x Voice_Format) Enum() *Voice_Format {
	p := new(Voice_Format)
	*p = x
	return p
}

func (x Voice_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Voice_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_msg_msg_proto_enumTypes[1].Descriptor()
}

func (Voice_Format) Type() protoreflect.EnumType {
	return &file_api_msg_msg_proto_enumTypes[1]
}

func (x Voice_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Voice_Format.Descriptor instead.
func (Voice_Format) EnumDescriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{1, 0}
}

// 视频类型
type Video_Format int32

const (
	Video_FORMAT_UNSPECIFIED Video_Format = 0 // 未知
	Video_FORMAT_MP4         Video_Format = 1 // MP4格式
)

// Enum value maps for Video_Format.
var (
	Video_Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_MP4",
	}
	Video_Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_MP4":         1,
	}
)

func (x Video_Format) Enum() *Video_Format {
	p := new(Video_Format)
	*p = x
	return p
}

func (x Video_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Video_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_msg_msg_proto_enumTypes[2].Descriptor()
}

func (Video_Format) Type() protoreflect.EnumType {
	return &file_api_msg_msg_proto_enumTypes[2]
}

func (x Video_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Video_Format.Descriptor instead.
func (Video_Format) EnumDescriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{2, 0}
}

// 文件类型
type File_Format int32

const (
	File_FORMAT_UNSPECIFIED File_Format = 0 // 未知
	File_FORMAT_PDF         File_Format = 1 // PDF格式
)

// Enum value maps for File_Format.
var (
	File_Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_PDF",
	}
	File_Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_PDF":         1,
	}
)

func (x File_Format) Enum() *File_Format {
	p := new(File_Format)
	*p = x
	return p
}

func (x File_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (File_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_msg_msg_proto_enumTypes[3].Descriptor()
}

func (File_Format) Type() protoreflect.EnumType {
	return &file_api_msg_msg_proto_enumTypes[3]
}

func (x File_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use File_Format.Descriptor instead.
func (File_Format) EnumDescriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{3, 0}
}

// 接收者类型
type Receiver_Type int32

const (
	Receiver_TYPE_UNSPECIFIED Receiver_Type = 0 // 未知
	Receiver_TYPE_USER        Receiver_Type = 1 // 用户
	Receiver_TYPE_GROUP       Receiver_Type = 2 // 群
)

// Enum value maps for Receiver_Type.
var (
	Receiver_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_USER",
		2: "TYPE_GROUP",
	}
	Receiver_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_USER":        1,
		"TYPE_GROUP":       2,
	}
)

func (x Receiver_Type) Enum() *Receiver_Type {
	p := new(Receiver_Type)
	*p = x
	return p
}

func (x Receiver_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Receiver_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_msg_msg_proto_enumTypes[4].Descriptor()
}

func (Receiver_Type) Type() protoreflect.EnumType {
	return &file_api_msg_msg_proto_enumTypes[4]
}

func (x Receiver_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Receiver_Type.Descriptor instead.
func (Receiver_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{5, 0}
}

// 发送者类型
type Sender_Type int32

const (
	Sender_TYPE_UNSPECIFIED Sender_Type = 0 // 未知
	Sender_TYPE_USER        Sender_Type = 1 // 用户
	Sender_TYPE_SYS         Sender_Type = 2 // 系统
)

// Enum value maps for Sender_Type.
var (
	Sender_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_USER",
		2: "TYPE_SYS",
	}
	Sender_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_USER":        1,
		"TYPE_SYS":         2,
	}
)

func (x Sender_Type) Enum() *Sender_Type {
	p := new(Sender_Type)
	*p = x
	return p
}

func (x Sender_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sender_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_msg_msg_proto_enumTypes[5].Descriptor()
}

func (Sender_Type) Type() protoreflect.EnumType {
	return &file_api_msg_msg_proto_enumTypes[5]
}

func (x Sender_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sender_Type.Descriptor instead.
func (Sender_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{6, 0}
}

// 图片
type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                              // 地址
	Width  uint32       `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`                         // 宽
	Height uint32       `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                       // 高
	Format Image_Format `protobuf:"varint,4,opt,name=format,proto3,enum=msg.Image_Format" json:"format,omitempty"` // 图片类型
	Size   uint32       `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`                           // 大小，单位B
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetFormat() Image_Format {
	if x != nil {
		return x.Format
	}
	return Image_FORMAT_UNSPECIFIED
}

func (x *Image) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 语音
type Voice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                              // 地址
	Duration uint32       `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`                   // 时长，单位秒
	Format   Voice_Format `protobuf:"varint,3,opt,name=format,proto3,enum=msg.Voice_Format" json:"format,omitempty"` // 语音类型
	Size     uint32       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                           // 大小，单位B
}

func (x *Voice) Reset() {
	*x = Voice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voice) ProtoMessage() {}

func (x *Voice) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voice.ProtoReflect.Descriptor instead.
func (*Voice) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Voice) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Voice) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Voice) GetFormat() Voice_Format {
	if x != nil {
		return x.Format
	}
	return Voice_FORMAT_UNSPECIFIED
}

func (x *Voice) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 视频
type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                              // 地址
	Duration uint32       `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`                   // 时长，单位秒
	Format   Video_Format `protobuf:"varint,3,opt,name=format,proto3,enum=msg.Video_Format" json:"format,omitempty"` // 视频类型
	Size     uint32       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                           // 大小，单位B
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Video) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetFormat() Video_Format {
	if x != nil {
		return x.Format
	}
	return Video_FORMAT_UNSPECIFIED
}

func (x *Video) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 文件
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string      `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                             // 地址
	Name   string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                           // 文件名
	Format File_Format `protobuf:"varint,3,opt,name=format,proto3,enum=msg.File_Format" json:"format,omitempty"` // 文件类型
	Size   uint32      `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                          // 大小，单位B
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetFormat() File_Format {
	if x != nil {
		return x.Format
	}
	return File_FORMAT_UNSPECIFIED
}

func (x *File) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 消息，消息会持久化存储
// 通过客户端信箱编号同步机制，保证消息可靠性，同时客户端需要保证消息被成功处理
// 消息通过事件推送给客户端
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                       // 信箱拥有者用户编号
	MailBoxMsgId uint64    `protobuf:"varint,2,opt,name=mail_box_msg_id,json=mailBoxMsgId,proto3" json:"mail_box_msg_id,omitempty"` // 信箱里消息编号，每个人一个信箱，信箱里消息编号会递增（保证不丢失消息）
	MsgId        uint64    `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                          // 消息编号，全局唯一，根据到达服务器时间生成，可以用户消息排序（保证有序性）
	Sender       *Sender   `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`                                      // 发送者
	Receiver     *Receiver `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`                                  // 接收者
	SendTime     uint64    `protobuf:"varint,6,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`                 // 发送时间
	ArrivalTime  uint64    `protobuf:"varint,7,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`        // 到达服务器时间
	// 发送者的一个终端的一个请求的唯一标识
	// （避免消息重复，比如消息发送成功，但是用户没有收到响应（断网），
	// 再回来的时候同步消息，通过CorrelationID就可以把发送失败的消息设置为发送成功）
	// 唯一标识可以是 UUID_IncrementID
	CorrelationId string `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// 消息内容
	//
	// Types that are assignable to Content:
	//	*Msg_TextMsg
	//	*Msg_ImageMsg
	//	*Msg_VoiceMsg
	//	*Msg_VideoMsg
	//	*Msg_FileMsg
	//	*Msg_WithdrawMsg
	//	*Msg_TipMsg
	//	*Msg_EventMsg
	Content isMsg_Content `protobuf_oneof:"content"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *Msg) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Msg) GetMailBoxMsgId() uint64 {
	if x != nil {
		return x.MailBoxMsgId
	}
	return 0
}

func (x *Msg) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Msg) GetSender() *Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Msg) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Msg) GetSendTime() uint64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Msg) GetArrivalTime() uint64 {
	if x != nil {
		return x.ArrivalTime
	}
	return 0
}

func (x *Msg) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (m *Msg) GetContent() isMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Msg) GetTextMsg() *TextMsg {
	if x, ok := x.GetContent().(*Msg_TextMsg); ok {
		return x.TextMsg
	}
	return nil
}

func (x *Msg) GetImageMsg() *ImageMsg {
	if x, ok := x.GetContent().(*Msg_ImageMsg); ok {
		return x.ImageMsg
	}
	return nil
}

func (x *Msg) GetVoiceMsg() *VoiceMsg {
	if x, ok := x.GetContent().(*Msg_VoiceMsg); ok {
		return x.VoiceMsg
	}
	return nil
}

func (x *Msg) GetVideoMsg() *VideoMsg {
	if x, ok := x.GetContent().(*Msg_VideoMsg); ok {
		return x.VideoMsg
	}
	return nil
}

func (x *Msg) GetFileMsg() *FileMsg {
	if x, ok := x.GetContent().(*Msg_FileMsg); ok {
		return x.FileMsg
	}
	return nil
}

func (x *Msg) GetWithdrawMsg() *WithdrawMsg {
	if x, ok := x.GetContent().(*Msg_WithdrawMsg); ok {
		return x.WithdrawMsg
	}
	return nil
}

func (x *Msg) GetTipMsg() *TipMsg {
	if x, ok := x.GetContent().(*Msg_TipMsg); ok {
		return x.TipMsg
	}
	return nil
}

func (x *Msg) GetEventMsg() *EventMsg {
	if x, ok := x.GetContent().(*Msg_EventMsg); ok {
		return x.EventMsg
	}
	return nil
}

type isMsg_Content interface {
	isMsg_Content()
}

type Msg_TextMsg struct {
	TextMsg *TextMsg `protobuf:"bytes,9,opt,name=text_msg,json=textMsg,proto3,oneof"`
}

type Msg_ImageMsg struct {
	ImageMsg *ImageMsg `protobuf:"bytes,10,opt,name=image_msg,json=imageMsg,proto3,oneof"`
}

type Msg_VoiceMsg struct {
	VoiceMsg *VoiceMsg `protobuf:"bytes,11,opt,name=voice_msg,json=voiceMsg,proto3,oneof"`
}

type Msg_VideoMsg struct {
	VideoMsg *VideoMsg `protobuf:"bytes,12,opt,name=video_msg,json=videoMsg,proto3,oneof"`
}

type Msg_FileMsg struct {
	FileMsg *FileMsg `protobuf:"bytes,13,opt,name=file_msg,json=fileMsg,proto3,oneof"`
}

type Msg_WithdrawMsg struct {
	WithdrawMsg *WithdrawMsg `protobuf:"bytes,14,opt,name=withdraw_msg,json=withdrawMsg,proto3,oneof"`
}

type Msg_TipMsg struct {
	TipMsg *TipMsg `protobuf:"bytes,15,opt,name=tip_msg,json=tipMsg,proto3,oneof"`
}

type Msg_EventMsg struct {
	EventMsg *EventMsg `protobuf:"bytes,16,opt,name=event_msg,json=eventMsg,proto3,oneof"`
}

func (*Msg_TextMsg) isMsg_Content() {}

func (*Msg_ImageMsg) isMsg_Content() {}

func (*Msg_VoiceMsg) isMsg_Content() {}

func (*Msg_VideoMsg) isMsg_Content() {}

func (*Msg_FileMsg) isMsg_Content() {}

func (*Msg_WithdrawMsg) isMsg_Content() {}

func (*Msg_TipMsg) isMsg_Content() {}

func (*Msg_EventMsg) isMsg_Content() {}

// 接收者
type Receiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       Receiver_Type `protobuf:"varint,1,opt,name=type,proto3,enum=msg.Receiver_Type" json:"type,omitempty"`        // 接收者类型
	ReceiverId uint64        `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 接收者编号
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *Receiver) GetType() Receiver_Type {
	if x != nil {
		return x.Type
	}
	return Receiver_TYPE_UNSPECIFIED
}

func (x *Receiver) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

// 发送者
type Sender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           Sender_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=msg.Sender_Type" json:"type,omitempty"`                                             // 发送者类型
	SenderId       uint64            `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                                          // 发送者编号
	SenderTerminal constant.Terminal `protobuf:"varint,3,opt,name=sender_terminal,json=senderTerminal,proto3,enum=constant.Terminal" json:"sender_terminal,omitempty"` // 发送者终端
}

func (x *Sender) Reset() {
	*x = Sender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sender) ProtoMessage() {}

func (x *Sender) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sender.ProtoReflect.Descriptor instead.
func (*Sender) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *Sender) GetType() Sender_Type {
	if x != nil {
		return x.Type
	}
	return Sender_TYPE_UNSPECIFIED
}

func (x *Sender) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Sender) GetSenderTerminal() constant.Terminal {
	if x != nil {
		return x.SenderTerminal
	}
	return constant.Terminal(0)
}

// 文本消息
type TextMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content     string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                               // 文本消息内容
	IsAtAll     bool     `protobuf:"varint,2,opt,name=is_at_all,json=isAtAll,proto3" json:"is_at_all,omitempty"`             // 是否@所有人
	IsNotice    bool     `protobuf:"varint,3,opt,name=is_notice,json=isNotice,proto3" json:"is_notice,omitempty"`            // 是否群公告
	AtUserIds   []string `protobuf:"bytes,4,rep,name=at_user_ids,json=atUserIds,proto3" json:"at_user_ids,omitempty"`        // 被@的用户
	QuotedMsgId uint64   `protobuf:"varint,5,opt,name=quoted_msg_id,json=quotedMsgId,proto3" json:"quoted_msg_id,omitempty"` // 被引用消息编号
}

func (x *TextMsg) Reset() {
	*x = TextMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMsg) ProtoMessage() {}

func (x *TextMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMsg.ProtoReflect.Descriptor instead.
func (*TextMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{7}
}

func (x *TextMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextMsg) GetIsAtAll() bool {
	if x != nil {
		return x.IsAtAll
	}
	return false
}

func (x *TextMsg) GetIsNotice() bool {
	if x != nil {
		return x.IsNotice
	}
	return false
}

func (x *TextMsg) GetAtUserIds() []string {
	if x != nil {
		return x.AtUserIds
	}
	return nil
}

func (x *TextMsg) GetQuotedMsgId() uint64 {
	if x != nil {
		return x.QuotedMsgId
	}
	return 0
}

// 图片消息
type ImageMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumbnail     *Image `protobuf:"bytes,1,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`                              // 缩略图
	OriginalImage *Image `protobuf:"bytes,2,opt,name=original_image,json=originalImage,proto3" json:"original_image,omitempty"` // 原图
}

func (x *ImageMsg) Reset() {
	*x = ImageMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMsg) ProtoMessage() {}

func (x *ImageMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMsg.ProtoReflect.Descriptor instead.
func (*ImageMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{8}
}

func (x *ImageMsg) GetThumbnail() *Image {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *ImageMsg) GetOriginalImage() *Image {
	if x != nil {
		return x.OriginalImage
	}
	return nil
}

// 语音消息
type VoiceMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voice *Voice `protobuf:"bytes,1,opt,name=voice,proto3" json:"voice,omitempty"` // 语音
}

func (x *VoiceMsg) Reset() {
	*x = VoiceMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoiceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceMsg) ProtoMessage() {}

func (x *VoiceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceMsg.ProtoReflect.Descriptor instead.
func (*VoiceMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{9}
}

func (x *VoiceMsg) GetVoice() *Voice {
	if x != nil {
		return x.Voice
	}
	return nil
}

// 视频消息
type VideoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Thumbnail *Image `protobuf:"bytes,1,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"` // 缩略图
	Video     *Video `protobuf:"bytes,2,opt,name=video,proto3" json:"video,omitempty"`         // 视频
}

func (x *VideoMsg) Reset() {
	*x = VideoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMsg) ProtoMessage() {}

func (x *VideoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMsg.ProtoReflect.Descriptor instead.
func (*VideoMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{10}
}

func (x *VideoMsg) GetThumbnail() *Image {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *VideoMsg) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

// 文件消息
type FileMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *File `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"` // 文件
}

func (x *FileMsg) Reset() {
	*x = FileMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMsg) ProtoMessage() {}

func (x *FileMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMsg.ProtoReflect.Descriptor instead.
func (*FileMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{11}
}

func (x *FileMsg) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

// 撤回消息
type WithdrawMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId uint64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"` // 被撤回消息的编号
}

func (x *WithdrawMsg) Reset() {
	*x = WithdrawMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMsg) ProtoMessage() {}

func (x *WithdrawMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMsg.ProtoReflect.Descriptor instead.
func (*WithdrawMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{12}
}

func (x *WithdrawMsg) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

// 提示消息
type TipMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 提示内容
	//
	// Types that are assignable to Content:
	//	*TipMsg_TextTip_
	//	*TipMsg_NickNameTextTip_
	Content isTipMsg_Content `protobuf_oneof:"content"`
}

func (x *TipMsg) Reset() {
	*x = TipMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipMsg) ProtoMessage() {}

func (x *TipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipMsg.ProtoReflect.Descriptor instead.
func (*TipMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{13}
}

func (m *TipMsg) GetContent() isTipMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *TipMsg) GetTextTip() *TipMsg_TextTip {
	if x, ok := x.GetContent().(*TipMsg_TextTip_); ok {
		return x.TextTip
	}
	return nil
}

func (x *TipMsg) GetNickNameTextTip() *TipMsg_NickNameTextTip {
	if x, ok := x.GetContent().(*TipMsg_NickNameTextTip_); ok {
		return x.NickNameTextTip
	}
	return nil
}

type isTipMsg_Content interface {
	isTipMsg_Content()
}

type TipMsg_TextTip_ struct {
	TextTip *TipMsg_TextTip `protobuf:"bytes,1,opt,name=text_tip,json=textTip,proto3,oneof"`
}

type TipMsg_NickNameTextTip_ struct {
	NickNameTextTip *TipMsg_NickNameTextTip `protobuf:"bytes,2,opt,name=nick_name_text_tip,json=nickNameTextTip,proto3,oneof"`
}

func (*TipMsg_TextTip_) isTipMsg_Content() {}

func (*TipMsg_NickNameTextTip_) isTipMsg_Content() {}

// 事件消息
// 事件消息用于需要保证客户端能够收到的事件
// 本质上是消息，但是一般不用于展示，只用于通知
type EventMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 事件消息内容
	//
	// Types that are assignable to Content:
	//	*EventMsg_NewFriend_
	//	*EventMsg_FriendInfoChange_
	//	*EventMsg_DeleteFriend_
	//	*EventMsg_NewAddFriendApplication_
	//	*EventMsg_AddFriendApplicationStatusChange_
	//	*EventMsg_NewGroup_
	//	*EventMsg_GroupInfoChange_
	//	*EventMsg_GroupMemberInfoChange_
	//	*EventMsg_NewJoinGroupEvent_
	//	*EventMsg_JoinGroupEventChange_
	Content isEventMsg_Content `protobuf_oneof:"content"`
}

func (x *EventMsg) Reset() {
	*x = EventMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg) ProtoMessage() {}

func (x *EventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg.ProtoReflect.Descriptor instead.
func (*EventMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14}
}

func (m *EventMsg) GetContent() isEventMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *EventMsg) GetNewFriend() *EventMsg_NewFriend {
	if x, ok := x.GetContent().(*EventMsg_NewFriend_); ok {
		return x.NewFriend
	}
	return nil
}

func (x *EventMsg) GetFriendInfoChange() *EventMsg_FriendInfoChange {
	if x, ok := x.GetContent().(*EventMsg_FriendInfoChange_); ok {
		return x.FriendInfoChange
	}
	return nil
}

func (x *EventMsg) GetDeleteFriend() *EventMsg_DeleteFriend {
	if x, ok := x.GetContent().(*EventMsg_DeleteFriend_); ok {
		return x.DeleteFriend
	}
	return nil
}

func (x *EventMsg) GetNewAddFriendApplication() *EventMsg_NewAddFriendApplication {
	if x, ok := x.GetContent().(*EventMsg_NewAddFriendApplication_); ok {
		return x.NewAddFriendApplication
	}
	return nil
}

func (x *EventMsg) GetAddFriendApplicationStatusChange() *EventMsg_AddFriendApplicationStatusChange {
	if x, ok := x.GetContent().(*EventMsg_AddFriendApplicationStatusChange_); ok {
		return x.AddFriendApplicationStatusChange
	}
	return nil
}

func (x *EventMsg) GetNewGroup() *EventMsg_NewGroup {
	if x, ok := x.GetContent().(*EventMsg_NewGroup_); ok {
		return x.NewGroup
	}
	return nil
}

func (x *EventMsg) GetGroupInfoChange() *EventMsg_GroupInfoChange {
	if x, ok := x.GetContent().(*EventMsg_GroupInfoChange_); ok {
		return x.GroupInfoChange
	}
	return nil
}

func (x *EventMsg) GetGroupMemberInfoChange() *EventMsg_GroupMemberInfoChange {
	if x, ok := x.GetContent().(*EventMsg_GroupMemberInfoChange_); ok {
		return x.GroupMemberInfoChange
	}
	return nil
}

func (x *EventMsg) GetNewJoinGroupEvent() *EventMsg_NewJoinGroupEvent {
	if x, ok := x.GetContent().(*EventMsg_NewJoinGroupEvent_); ok {
		return x.NewJoinGroupEvent
	}
	return nil
}

func (x *EventMsg) GetJoinGroupEventChange() *EventMsg_JoinGroupEventChange {
	if x, ok := x.GetContent().(*EventMsg_JoinGroupEventChange_); ok {
		return x.JoinGroupEventChange
	}
	return nil
}

type isEventMsg_Content interface {
	isEventMsg_Content()
}

type EventMsg_NewFriend_ struct {
	NewFriend *EventMsg_NewFriend `protobuf:"bytes,1,opt,name=new_friend,json=newFriend,proto3,oneof"`
}

type EventMsg_FriendInfoChange_ struct {
	FriendInfoChange *EventMsg_FriendInfoChange `protobuf:"bytes,2,opt,name=friend_info_change,json=friendInfoChange,proto3,oneof"`
}

type EventMsg_DeleteFriend_ struct {
	DeleteFriend *EventMsg_DeleteFriend `protobuf:"bytes,3,opt,name=delete_friend,json=deleteFriend,proto3,oneof"`
}

type EventMsg_NewAddFriendApplication_ struct {
	NewAddFriendApplication *EventMsg_NewAddFriendApplication `protobuf:"bytes,4,opt,name=new_add_friend_application,json=newAddFriendApplication,proto3,oneof"`
}

type EventMsg_AddFriendApplicationStatusChange_ struct {
	AddFriendApplicationStatusChange *EventMsg_AddFriendApplicationStatusChange `protobuf:"bytes,5,opt,name=add_friend_application_status_change,json=addFriendApplicationStatusChange,proto3,oneof"`
}

type EventMsg_NewGroup_ struct {
	NewGroup *EventMsg_NewGroup `protobuf:"bytes,6,opt,name=new_group,json=newGroup,proto3,oneof"`
}

type EventMsg_GroupInfoChange_ struct {
	GroupInfoChange *EventMsg_GroupInfoChange `protobuf:"bytes,7,opt,name=group_info_change,json=groupInfoChange,proto3,oneof"`
}

type EventMsg_GroupMemberInfoChange_ struct {
	GroupMemberInfoChange *EventMsg_GroupMemberInfoChange `protobuf:"bytes,8,opt,name=group_member_info_change,json=groupMemberInfoChange,proto3,oneof"`
}

type EventMsg_NewJoinGroupEvent_ struct {
	NewJoinGroupEvent *EventMsg_NewJoinGroupEvent `protobuf:"bytes,9,opt,name=new_join_group_event,json=newJoinGroupEvent,proto3,oneof"`
}

type EventMsg_JoinGroupEventChange_ struct {
	JoinGroupEventChange *EventMsg_JoinGroupEventChange `protobuf:"bytes,10,opt,name=join_group_event_change,json=joinGroupEventChange,proto3,oneof"`
}

func (*EventMsg_NewFriend_) isEventMsg_Content() {}

func (*EventMsg_FriendInfoChange_) isEventMsg_Content() {}

func (*EventMsg_DeleteFriend_) isEventMsg_Content() {}

func (*EventMsg_NewAddFriendApplication_) isEventMsg_Content() {}

func (*EventMsg_AddFriendApplicationStatusChange_) isEventMsg_Content() {}

func (*EventMsg_NewGroup_) isEventMsg_Content() {}

func (*EventMsg_GroupInfoChange_) isEventMsg_Content() {}

func (*EventMsg_GroupMemberInfoChange_) isEventMsg_Content() {}

func (*EventMsg_NewJoinGroupEvent_) isEventMsg_Content() {}

func (*EventMsg_JoinGroupEventChange_) isEventMsg_Content() {}

// @存储模型
// 信箱消息
// 每个消息都会转换成信箱消息进行存储
type MailBoxMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *Msg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // 消息
}

func (x *MailBoxMsg) Reset() {
	*x = MailBoxMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailBoxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailBoxMsg) ProtoMessage() {}

func (x *MailBoxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailBoxMsg.ProtoReflect.Descriptor instead.
func (*MailBoxMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{15}
}

func (x *MailBoxMsg) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

// 文本提示
type TipMsg_TextTip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // 提示内容
}

func (x *TipMsg_TextTip) Reset() {
	*x = TipMsg_TextTip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipMsg_TextTip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipMsg_TextTip) ProtoMessage() {}

func (x *TipMsg_TextTip) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipMsg_TextTip.ProtoReflect.Descriptor instead.
func (*TipMsg_TextTip) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{13, 0}
}

func (x *TipMsg_TextTip) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 昵称文本提示
type TipMsg_NickNameTextTip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format        string                                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`                                      // 格式字符串
	NickNameTexts []*TipMsg_NickNameTextTip_NickNameText `protobuf:"bytes,2,rep,name=nick_name_texts,json=nickNameTexts,proto3" json:"nick_name_texts,omitempty"` // 昵称文本
}

func (x *TipMsg_NickNameTextTip) Reset() {
	*x = TipMsg_NickNameTextTip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipMsg_NickNameTextTip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipMsg_NickNameTextTip) ProtoMessage() {}

func (x *TipMsg_NickNameTextTip) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipMsg_NickNameTextTip.ProtoReflect.Descriptor instead.
func (*TipMsg_NickNameTextTip) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{13, 1}
}

func (x *TipMsg_NickNameTextTip) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TipMsg_NickNameTextTip) GetNickNameTexts() []*TipMsg_NickNameTextTip_NickNameText {
	if x != nil {
		return x.NickNameTexts
	}
	return nil
}

// 昵称文本
type TipMsg_NickNameTextTip_NickNameText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户编号
	NickName string `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` // 昵称
}

func (x *TipMsg_NickNameTextTip_NickNameText) Reset() {
	*x = TipMsg_NickNameTextTip_NickNameText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipMsg_NickNameTextTip_NickNameText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipMsg_NickNameTextTip_NickNameText) ProtoMessage() {}

func (x *TipMsg_NickNameTextTip_NickNameText) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipMsg_NickNameTextTip_NickNameText.ProtoReflect.Descriptor instead.
func (*TipMsg_NickNameTextTip_NickNameText) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{13, 1, 0}
}

func (x *TipMsg_NickNameTextTip_NickNameText) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TipMsg_NickNameTextTip_NickNameText) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

// 新的好友事件消息（你已添加了xx，现在可以开始聊天了tip）
type EventMsg_NewFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 用户编号
}

func (x *EventMsg_NewFriend) Reset() {
	*x = EventMsg_NewFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_NewFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_NewFriend) ProtoMessage() {}

func (x *EventMsg_NewFriend) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_NewFriend.ProtoReflect.Descriptor instead.
func (*EventMsg_NewFriend) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 0}
}

func (x *EventMsg_NewFriend) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 好友信息改变事件消息
type EventMsg_FriendInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 用户编号
}

func (x *EventMsg_FriendInfoChange) Reset() {
	*x = EventMsg_FriendInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_FriendInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_FriendInfoChange) ProtoMessage() {}

func (x *EventMsg_FriendInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_FriendInfoChange.ProtoReflect.Descriptor instead.
func (*EventMsg_FriendInfoChange) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 1}
}

func (x *EventMsg_FriendInfoChange) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 删除好友事件消息（对方删除了你tip）
type EventMsg_DeleteFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 用户编号
}

func (x *EventMsg_DeleteFriend) Reset() {
	*x = EventMsg_DeleteFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_DeleteFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_DeleteFriend) ProtoMessage() {}

func (x *EventMsg_DeleteFriend) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_DeleteFriend.ProtoReflect.Descriptor instead.
func (*EventMsg_DeleteFriend) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 2}
}

func (x *EventMsg_DeleteFriend) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 新的添加好友申请事件消息
type EventMsg_NewAddFriendApplication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplicationId uint64 `protobuf:"varint,1,opt,name=add_friend_application_id,json=addFriendApplicationId,proto3" json:"add_friend_application_id,omitempty"` // 好友申请编号
}

func (x *EventMsg_NewAddFriendApplication) Reset() {
	*x = EventMsg_NewAddFriendApplication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_NewAddFriendApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_NewAddFriendApplication) ProtoMessage() {}

func (x *EventMsg_NewAddFriendApplication) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_NewAddFriendApplication.ProtoReflect.Descriptor instead.
func (*EventMsg_NewAddFriendApplication) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 3}
}

func (x *EventMsg_NewAddFriendApplication) GetAddFriendApplicationId() uint64 {
	if x != nil {
		return x.AddFriendApplicationId
	}
	return 0
}

// 添加好友申请状态改变事件消息
type EventMsg_AddFriendApplicationStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplicationId uint64 `protobuf:"varint,1,opt,name=add_friend_application_id,json=addFriendApplicationId,proto3" json:"add_friend_application_id,omitempty"` // 状态改变的添加好友申请编号
}

func (x *EventMsg_AddFriendApplicationStatusChange) Reset() {
	*x = EventMsg_AddFriendApplicationStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_AddFriendApplicationStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_AddFriendApplicationStatusChange) ProtoMessage() {}

func (x *EventMsg_AddFriendApplicationStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_AddFriendApplicationStatusChange.ProtoReflect.Descriptor instead.
func (*EventMsg_AddFriendApplicationStatusChange) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 4}
}

func (x *EventMsg_AddFriendApplicationStatusChange) GetAddFriendApplicationId() uint64 {
	if x != nil {
		return x.AddFriendApplicationId
	}
	return 0
}

// 新的群事件消息（xx邀请xx，xxx，xxx等加入了群聊tip，你通过扫描xx分享的二维码加入群聊tip，xx邀请你加入了群聊tip）
type EventMsg_NewGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId uint64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 群编号
}

func (x *EventMsg_NewGroup) Reset() {
	*x = EventMsg_NewGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_NewGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_NewGroup) ProtoMessage() {}

func (x *EventMsg_NewGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_NewGroup.ProtoReflect.Descriptor instead.
func (*EventMsg_NewGroup) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 5}
}

func (x *EventMsg_NewGroup) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群信息改变事件消息（头像、群名、群公告，xx修改群名为xx tip）
type EventMsg_GroupInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId uint64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 群编号
}

func (x *EventMsg_GroupInfoChange) Reset() {
	*x = EventMsg_GroupInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_GroupInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_GroupInfoChange) ProtoMessage() {}

func (x *EventMsg_GroupInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_GroupInfoChange.ProtoReflect.Descriptor instead.
func (*EventMsg_GroupInfoChange) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 6}
}

func (x *EventMsg_GroupInfoChange) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群成员信息改变事件消息（直接拉群群成员信息列表和本地比较进行同步）
// 群成员信息更改（换群主，管理员变动，xx成为了新的群主tip，xx成为了新的管理员）
// 群成员加入（加入，邀请加入，xx通过扫描xx分析的二维码进群tip，xx邀请xx，xx，xx加入了群聊tip）
// 群成员退出（退出，被踢，xx退出了群聊tip，xx被踢出群聊tip）
type EventMsg_GroupMemberInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId uint64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 群编号
}

func (x *EventMsg_GroupMemberInfoChange) Reset() {
	*x = EventMsg_GroupMemberInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_GroupMemberInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_GroupMemberInfoChange) ProtoMessage() {}

func (x *EventMsg_GroupMemberInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_GroupMemberInfoChange.ProtoReflect.Descriptor instead.
func (*EventMsg_GroupMemberInfoChange) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 7}
}

func (x *EventMsg_GroupMemberInfoChange) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 新的入群事件事件消息
type EventMsg_NewJoinGroupEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinGroupEventId uint64 `protobuf:"varint,1,opt,name=join_group_event_id,json=joinGroupEventId,proto3" json:"join_group_event_id,omitempty"` // 入群事件编号
}

func (x *EventMsg_NewJoinGroupEvent) Reset() {
	*x = EventMsg_NewJoinGroupEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_NewJoinGroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_NewJoinGroupEvent) ProtoMessage() {}

func (x *EventMsg_NewJoinGroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_NewJoinGroupEvent.ProtoReflect.Descriptor instead.
func (*EventMsg_NewJoinGroupEvent) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 8}
}

func (x *EventMsg_NewJoinGroupEvent) GetJoinGroupEventId() uint64 {
	if x != nil {
		return x.JoinGroupEventId
	}
	return 0
}

// 入群事件改变事件消息
type EventMsg_JoinGroupEventChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinGroupEventId uint64 `protobuf:"varint,1,opt,name=join_group_event_id,json=joinGroupEventId,proto3" json:"join_group_event_id,omitempty"` // 入群事件编号
}

func (x *EventMsg_JoinGroupEventChange) Reset() {
	*x = EventMsg_JoinGroupEventChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_msg_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMsg_JoinGroupEventChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMsg_JoinGroupEventChange) ProtoMessage() {}

func (x *EventMsg_JoinGroupEventChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_msg_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMsg_JoinGroupEventChange.ProtoReflect.Descriptor instead.
func (*EventMsg_JoinGroupEventChange) Descriptor() ([]byte, []int) {
	return file_api_msg_msg_proto_rawDescGZIP(), []int{14, 9}
}

func (x *EventMsg_JoinGroupEventChange) GetJoinGroupEventId() uint64 {
	if x != nil {
		return x.JoinGroupEventId
	}
	return 0
}

var File_api_msg_msg_proto protoreflect.FileDescriptor

var file_api_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x01, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x29, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x40,
	0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x4f, 0x52, 0x4d,
	0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x4a, 0x50, 0x47, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x50, 0x4e, 0x47, 0x10, 0x02,
	0x22, 0xa6, 0x01, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56,
	0x6f, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x30, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x4f, 0x52,
	0x4d, 0x41, 0x54, 0x5f, 0x4d, 0x50, 0x33, 0x10, 0x01, 0x22, 0xa6, 0x01, 0x0a, 0x05, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x29, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x30, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x4f,
	0x52, 0x4d, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x4d, 0x50, 0x34,
	0x10, 0x01, 0x22, 0x9c, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x30, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x4f, 0x52,
	0x4d, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x50, 0x44, 0x46, 0x10,
	0x01, 0x22, 0x8b, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x0f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x61, 0x69,
	0x6c, 0x42, 0x6f, 0x78, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x74, 0x65, 0x78, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x07, 0x74, 0x65, 0x78, 0x74, 0x4d,
	0x73, 0x67, 0x12, 0x2c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x2c, 0x0a, 0x09, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4d,
	0x73, 0x67, 0x48, 0x00, 0x52, 0x08, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x2c,
	0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x73, 0x67,
	0x48, 0x00, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x29, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x07,
	0x66, 0x69, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x35, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x73, 0x67, 0x48,
	0x00, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4d, 0x73, 0x67, 0x12, 0x26,
	0x0a, 0x07, 0x74, 0x69, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x06,
	0x74, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x2c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x90, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x10, 0x02, 0x22, 0xc3, 0x01, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x3b, 0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x0e, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x22, 0x39, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x10, 0x02, 0x22, 0xa0, 0x01, 0x0a, 0x07, 0x54, 0x65, 0x78,
	0x74, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x74, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x64, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x08, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x12, 0x31, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x08, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x20, 0x0a, 0x05, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x05, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x22, 0x56, 0x0a, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x28,
	0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x09, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x28, 0x0a, 0x07, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x22, 0x24, 0x0a, 0x0b, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x4d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0xfa, 0x02, 0x0a, 0x06, 0x54,
	0x69, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x69,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x69,
	0x70, 0x4d, 0x73, 0x67, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x54, 0x69, 0x70, 0x48, 0x00, 0x52, 0x07,
	0x74, 0x65, 0x78, 0x74, 0x54, 0x69, 0x70, 0x12, 0x4a, 0x0a, 0x12, 0x6e, 0x69, 0x63, 0x6b, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x69, 0x70, 0x4d, 0x73, 0x67,
	0x2e, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x54, 0x69, 0x70,
	0x48, 0x00, 0x52, 0x0f, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74,
	0x54, 0x69, 0x70, 0x1a, 0x23, 0x0a, 0x07, 0x54, 0x65, 0x78, 0x74, 0x54, 0x69, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0xc1, 0x01, 0x0a, 0x0f, 0x4e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x54, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x50, 0x0a, 0x0f, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x54, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x2e, 0x4e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x54, 0x69, 0x70, 0x2e, 0x4e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x0d, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x54, 0x65, 0x78, 0x74, 0x73, 0x1a, 0x44, 0x0a, 0x0c, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xb1, 0x0b, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x4e,
	0x0a, 0x12, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x10, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x41,
	0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x12, 0x64, 0x0a, 0x1a, 0x6e, 0x65, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x17,
	0x6e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x80, 0x01, 0x0a, 0x24, 0x61, 0x64, 0x64, 0x5f,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x20, 0x61, 0x64, 0x64, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x6e, 0x65,
	0x77, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4e, 0x65, 0x77,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x4b, 0x0a, 0x11, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x5e,
	0x0a, 0x18, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x15, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x52,
	0x0a, 0x14, 0x6e, 0x65, 0x77, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x11, 0x6e, 0x65, 0x77, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x5b, 0x0a, 0x17, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d,
	0x73, 0x67, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x14, 0x6a, 0x6f, 0x69, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x1a,
	0x28, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x1a, 0x2f, 0x0a, 0x10, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x1a, 0x2b, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x1a, 0x54, 0x0a, 0x17, 0x4e, 0x65, 0x77, 0x41, 0x64,
	0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x19, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x61, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x5d, 0x0a,
	0x20, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x39, 0x0a, 0x19, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x61, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x25, 0x0a, 0x08,
	0x4e, 0x65, 0x77, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x1a, 0x2c, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x1a, 0x32, 0x0a, 0x15, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x1a, 0x42, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x13, 0x6a, 0x6f,
	0x69, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x45, 0x0a, 0x14, 0x4a, 0x6f, 0x69,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x2d, 0x0a, 0x13, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10,
	0x6a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0a, 0x4d,
	0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x61, 0x6f, 0x68, 0x75, 0x61, 0x73, 0x68, 0x69, 0x66, 0x75,
	0x2f, 0x68, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_msg_msg_proto_rawDescOnce sync.Once
	file_api_msg_msg_proto_rawDescData = file_api_msg_msg_proto_rawDesc
)

func file_api_msg_msg_proto_rawDescGZIP() []byte {
	file_api_msg_msg_proto_rawDescOnce.Do(func() {
		file_api_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_msg_msg_proto_rawDescData)
	})
	return file_api_msg_msg_proto_rawDescData
}

var file_api_msg_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_msg_msg_proto_goTypes = []interface{}{
	(Image_Format)(0),              // 0: msg.Image.Format
	(Voice_Format)(0),              // 1: msg.Voice.Format
	(Video_Format)(0),              // 2: msg.Video.Format
	(File_Format)(0),               // 3: msg.File.Format
	(Receiver_Type)(0),             // 4: msg.Receiver.Type
	(Sender_Type)(0),               // 5: msg.Sender.Type
	(*Image)(nil),                  // 6: msg.Image
	(*Voice)(nil),                  // 7: msg.Voice
	(*Video)(nil),                  // 8: msg.Video
	(*File)(nil),                   // 9: msg.File
	(*Msg)(nil),                    // 10: msg.Msg
	(*Receiver)(nil),               // 11: msg.Receiver
	(*Sender)(nil),                 // 12: msg.Sender
	(*TextMsg)(nil),                // 13: msg.TextMsg
	(*ImageMsg)(nil),               // 14: msg.ImageMsg
	(*VoiceMsg)(nil),               // 15: msg.VoiceMsg
	(*VideoMsg)(nil),               // 16: msg.VideoMsg
	(*FileMsg)(nil),                // 17: msg.FileMsg
	(*WithdrawMsg)(nil),            // 18: msg.WithdrawMsg
	(*TipMsg)(nil),                 // 19: msg.TipMsg
	(*EventMsg)(nil),               // 20: msg.EventMsg
	(*MailBoxMsg)(nil),             // 21: msg.MailBoxMsg
	(*TipMsg_TextTip)(nil),         // 22: msg.TipMsg.TextTip
	(*TipMsg_NickNameTextTip)(nil), // 23: msg.TipMsg.NickNameTextTip
	(*TipMsg_NickNameTextTip_NickNameText)(nil),       // 24: msg.TipMsg.NickNameTextTip.NickNameText
	(*EventMsg_NewFriend)(nil),                        // 25: msg.EventMsg.NewFriend
	(*EventMsg_FriendInfoChange)(nil),                 // 26: msg.EventMsg.FriendInfoChange
	(*EventMsg_DeleteFriend)(nil),                     // 27: msg.EventMsg.DeleteFriend
	(*EventMsg_NewAddFriendApplication)(nil),          // 28: msg.EventMsg.NewAddFriendApplication
	(*EventMsg_AddFriendApplicationStatusChange)(nil), // 29: msg.EventMsg.AddFriendApplicationStatusChange
	(*EventMsg_NewGroup)(nil),                         // 30: msg.EventMsg.NewGroup
	(*EventMsg_GroupInfoChange)(nil),                  // 31: msg.EventMsg.GroupInfoChange
	(*EventMsg_GroupMemberInfoChange)(nil),            // 32: msg.EventMsg.GroupMemberInfoChange
	(*EventMsg_NewJoinGroupEvent)(nil),                // 33: msg.EventMsg.NewJoinGroupEvent
	(*EventMsg_JoinGroupEventChange)(nil),             // 34: msg.EventMsg.JoinGroupEventChange
	(constant.Terminal)(0),                            // 35: constant.Terminal
}
var file_api_msg_msg_proto_depIdxs = []int32{
	0,  // 0: msg.Image.format:type_name -> msg.Image.Format
	1,  // 1: msg.Voice.format:type_name -> msg.Voice.Format
	2,  // 2: msg.Video.format:type_name -> msg.Video.Format
	3,  // 3: msg.File.format:type_name -> msg.File.Format
	12, // 4: msg.Msg.sender:type_name -> msg.Sender
	11, // 5: msg.Msg.receiver:type_name -> msg.Receiver
	13, // 6: msg.Msg.text_msg:type_name -> msg.TextMsg
	14, // 7: msg.Msg.image_msg:type_name -> msg.ImageMsg
	15, // 8: msg.Msg.voice_msg:type_name -> msg.VoiceMsg
	16, // 9: msg.Msg.video_msg:type_name -> msg.VideoMsg
	17, // 10: msg.Msg.file_msg:type_name -> msg.FileMsg
	18, // 11: msg.Msg.withdraw_msg:type_name -> msg.WithdrawMsg
	19, // 12: msg.Msg.tip_msg:type_name -> msg.TipMsg
	20, // 13: msg.Msg.event_msg:type_name -> msg.EventMsg
	4,  // 14: msg.Receiver.type:type_name -> msg.Receiver.Type
	5,  // 15: msg.Sender.type:type_name -> msg.Sender.Type
	35, // 16: msg.Sender.sender_terminal:type_name -> constant.Terminal
	6,  // 17: msg.ImageMsg.thumbnail:type_name -> msg.Image
	6,  // 18: msg.ImageMsg.original_image:type_name -> msg.Image
	7,  // 19: msg.VoiceMsg.voice:type_name -> msg.Voice
	6,  // 20: msg.VideoMsg.thumbnail:type_name -> msg.Image
	8,  // 21: msg.VideoMsg.video:type_name -> msg.Video
	9,  // 22: msg.FileMsg.file:type_name -> msg.File
	22, // 23: msg.TipMsg.text_tip:type_name -> msg.TipMsg.TextTip
	23, // 24: msg.TipMsg.nick_name_text_tip:type_name -> msg.TipMsg.NickNameTextTip
	25, // 25: msg.EventMsg.new_friend:type_name -> msg.EventMsg.NewFriend
	26, // 26: msg.EventMsg.friend_info_change:type_name -> msg.EventMsg.FriendInfoChange
	27, // 27: msg.EventMsg.delete_friend:type_name -> msg.EventMsg.DeleteFriend
	28, // 28: msg.EventMsg.new_add_friend_application:type_name -> msg.EventMsg.NewAddFriendApplication
	29, // 29: msg.EventMsg.add_friend_application_status_change:type_name -> msg.EventMsg.AddFriendApplicationStatusChange
	30, // 30: msg.EventMsg.new_group:type_name -> msg.EventMsg.NewGroup
	31, // 31: msg.EventMsg.group_info_change:type_name -> msg.EventMsg.GroupInfoChange
	32, // 32: msg.EventMsg.group_member_info_change:type_name -> msg.EventMsg.GroupMemberInfoChange
	33, // 33: msg.EventMsg.new_join_group_event:type_name -> msg.EventMsg.NewJoinGroupEvent
	34, // 34: msg.EventMsg.join_group_event_change:type_name -> msg.EventMsg.JoinGroupEventChange
	10, // 35: msg.MailBoxMsg.msg:type_name -> msg.Msg
	24, // 36: msg.TipMsg.NickNameTextTip.nick_name_texts:type_name -> msg.TipMsg.NickNameTextTip.NickNameText
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_api_msg_msg_proto_init() }
func file_api_msg_msg_proto_init() {
	if File_api_msg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_msg_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoiceMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailBoxMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipMsg_TextTip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipMsg_NickNameTextTip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipMsg_NickNameTextTip_NickNameText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_NewFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_FriendInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_DeleteFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_NewAddFriendApplication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_AddFriendApplicationStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_NewGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_GroupInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_GroupMemberInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_NewJoinGroupEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_msg_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMsg_JoinGroupEventChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_msg_msg_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Msg_TextMsg)(nil),
		(*Msg_ImageMsg)(nil),
		(*Msg_VoiceMsg)(nil),
		(*Msg_VideoMsg)(nil),
		(*Msg_FileMsg)(nil),
		(*Msg_WithdrawMsg)(nil),
		(*Msg_TipMsg)(nil),
		(*Msg_EventMsg)(nil),
	}
	file_api_msg_msg_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*TipMsg_TextTip_)(nil),
		(*TipMsg_NickNameTextTip_)(nil),
	}
	file_api_msg_msg_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*EventMsg_NewFriend_)(nil),
		(*EventMsg_FriendInfoChange_)(nil),
		(*EventMsg_DeleteFriend_)(nil),
		(*EventMsg_NewAddFriendApplication_)(nil),
		(*EventMsg_AddFriendApplicationStatusChange_)(nil),
		(*EventMsg_NewGroup_)(nil),
		(*EventMsg_GroupInfoChange_)(nil),
		(*EventMsg_GroupMemberInfoChange_)(nil),
		(*EventMsg_NewJoinGroupEvent_)(nil),
		(*EventMsg_JoinGroupEventChange_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_msg_msg_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_msg_msg_proto_goTypes,
		DependencyIndexes: file_api_msg_msg_proto_depIdxs,
		EnumInfos:         file_api_msg_msg_proto_enumTypes,
		MessageInfos:      file_api_msg_msg_proto_msgTypes,
	}.Build()
	File_api_msg_msg_proto = out.File
	file_api_msg_msg_proto_rawDesc = nil
	file_api_msg_msg_proto_goTypes = nil
	file_api_msg_msg_proto_depIdxs = nil
}
