// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: service/service/im/gateway/protocol/long.proto

package long

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type MsgType int32

const (
	MsgType_MsgTypeUnknown MsgType = 0 // 未知
	MsgType_MsgTypeText    MsgType = 1 // 文字
	MsgType_MsgTypeImage   MsgType = 2 // 图片
	MsgType_MsgTypeVoice   MsgType = 3 // 语音
	MsgType_MsgTypeVideo   MsgType = 4 // 视频
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MsgTypeUnknown",
		1: "MsgTypeText",
		2: "MsgTypeImage",
		3: "MsgTypeVoice",
		4: "MsgTypeVideo",
	}
	MsgType_value = map[string]int32{
		"MsgTypeUnknown": 0,
		"MsgTypeText":    1,
		"MsgTypeImage":   2,
		"MsgTypeVoice":   3,
		"MsgTypeVideo":   4,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_service_im_gateway_protocol_long_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_service_service_im_gateway_protocol_long_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{0}
}

// 接收者类型
type ReceiverType int32

const (
	ReceiverType_ReceiverTypeUnknown ReceiverType = 0 // 未知
	ReceiverType_ReceiverTypeUser    ReceiverType = 1 // 用户
	ReceiverType_ReceiverTypeGroup   ReceiverType = 2 // 群
)

// Enum value maps for ReceiverType.
var (
	ReceiverType_name = map[int32]string{
		0: "ReceiverTypeUnknown",
		1: "ReceiverTypeUser",
		2: "ReceiverTypeGroup",
	}
	ReceiverType_value = map[string]int32{
		"ReceiverTypeUnknown": 0,
		"ReceiverTypeUser":    1,
		"ReceiverTypeGroup":   2,
	}
)

func (x ReceiverType) Enum() *ReceiverType {
	p := new(ReceiverType)
	*p = x
	return p
}

func (x ReceiverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiverType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_service_im_gateway_protocol_long_proto_enumTypes[1].Descriptor()
}

func (ReceiverType) Type() protoreflect.EnumType {
	return &file_service_service_im_gateway_protocol_long_proto_enumTypes[1]
}

func (x ReceiverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiverType.Descriptor instead.
func (ReceiverType) EnumDescriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{1}
}

// 事件类型
type EventType int32

const (
	EventType_EventTypeUnknown     EventType = 0 // 未知
	EventType_EventTypeResponse    EventType = 1 // 响应
	EventType_EventTypeNewMsg      EventType = 2 // 新消息
	EventType_EventTypeWithdrawMsg EventType = 3 // 撤回消息
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EventTypeUnknown",
		1: "EventTypeResponse",
		2: "EventTypeNewMsg",
		3: "EventTypeWithdrawMsg",
	}
	EventType_value = map[string]int32{
		"EventTypeUnknown":     0,
		"EventTypeResponse":    1,
		"EventTypeNewMsg":      2,
		"EventTypeWithdrawMsg": 3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_service_im_gateway_protocol_long_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_service_service_im_gateway_protocol_long_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{2}
}

// 接收者
type Receiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       ReceiverType `protobuf:"varint,1,opt,name=Type,proto3,enum=him.ReceiverType" json:"Type,omitempty"` // 接收者类型
	ReceiverID uint64       `protobuf:"varint,2,opt,name=ReceiverID,proto3" json:"ReceiverID,omitempty"`           // 接收者编号
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{0}
}

func (x *Receiver) GetType() ReceiverType {
	if x != nil {
		return x.Type
	}
	return ReceiverType_ReceiverTypeUnknown
}

func (x *Receiver) GetReceiverID() uint64 {
	if x != nil {
		return x.ReceiverID
	}
	return 0
}

// 请求
type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID uint64    `protobuf:"varint,1,opt,name=CorrelationID,proto3" json:"CorrelationID,omitempty"` // 请求唯一标识
	Type          MsgType   `protobuf:"varint,2,opt,name=Type,proto3,enum=him.MsgType" json:"Type,omitempty"`  // 消息类型
	Receiver      *Receiver `protobuf:"bytes,3,opt,name=Receiver,proto3" json:"Receiver,omitempty"`            // 接收者
	Content       []byte    `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`              // 消息内容
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{1}
}

func (x *Req) GetCorrelationID() uint64 {
	if x != nil {
		return x.CorrelationID
	}
	return 0
}

func (x *Req) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MsgTypeUnknown
}

func (x *Req) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Req) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// 响应
type Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID uint64 `protobuf:"varint,1,opt,name=CorrelationID,proto3" json:"CorrelationID,omitempty"` // 请求唯一标识
	MsgID         uint64 `protobuf:"varint,2,opt,name=MsgID,proto3" json:"MsgID,omitempty"`                 // 消息编号
	SendTime      uint64 `protobuf:"varint,3,opt,name=SendTime,proto3" json:"SendTime,omitempty"`           // 发送时间
}

func (x *Rsp) Reset() {
	*x = Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsp) ProtoMessage() {}

func (x *Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsp.ProtoReflect.Descriptor instead.
func (*Rsp) Descriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{2}
}

func (x *Rsp) GetCorrelationID() uint64 {
	if x != nil {
		return x.CorrelationID
	}
	return 0
}

func (x *Rsp) GetMsgID() uint64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *Rsp) GetSendTime() uint64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

// 事件
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    EventType `protobuf:"varint,1,opt,name=Type,proto3,enum=him.EventType" json:"Type,omitempty"` // 事件类型
	Content []byte    `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`               // 事件内容
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_service_service_im_gateway_protocol_long_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_service_service_im_gateway_protocol_long_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EventTypeUnknown
}

func (x *Event) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_service_service_im_gateway_protocol_long_proto protoreflect.FileDescriptor

var file_service_service_im_gateway_protocol_long_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x69, 0x6d, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6c, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x68, 0x69, 0x6d, 0x22, 0x51, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x12, 0x25, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x68, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x44, 0x22, 0x92, 0x01, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x68, 0x69, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68, 0x69, 0x6d,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5d, 0x0a,
	0x03, 0x52, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x43, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73,
	0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x05,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x68, 0x69, 0x6d, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2a, 0x64, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x56, 0x6f, 0x69, 0x63, 0x65, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x04, 0x2a, 0x54, 0x0a, 0x0c, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x02, 0x2a,
	0x67, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x10, 0x02, 0x12, 0x18,
	0x0a, 0x14, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x4d, 0x73, 0x67, 0x10, 0x03, 0x42, 0x2a, 0x5a, 0x28, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6d, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x6c, 0x6f, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_service_im_gateway_protocol_long_proto_rawDescOnce sync.Once
	file_service_service_im_gateway_protocol_long_proto_rawDescData = file_service_service_im_gateway_protocol_long_proto_rawDesc
)

func file_service_service_im_gateway_protocol_long_proto_rawDescGZIP() []byte {
	file_service_service_im_gateway_protocol_long_proto_rawDescOnce.Do(func() {
		file_service_service_im_gateway_protocol_long_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_service_im_gateway_protocol_long_proto_rawDescData)
	})
	return file_service_service_im_gateway_protocol_long_proto_rawDescData
}

var file_service_service_im_gateway_protocol_long_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_service_service_im_gateway_protocol_long_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_service_im_gateway_protocol_long_proto_goTypes = []interface{}{
	(MsgType)(0),      // 0: him.MsgType
	(ReceiverType)(0), // 1: him.ReceiverType
	(EventType)(0),    // 2: him.EventType
	(*Receiver)(nil),  // 3: him.Receiver
	(*Req)(nil),       // 4: him.Req
	(*Rsp)(nil),       // 5: him.Rsp
	(*Event)(nil),     // 6: him.Event
}
var file_service_service_im_gateway_protocol_long_proto_depIdxs = []int32{
	1, // 0: him.Receiver.Type:type_name -> him.ReceiverType
	0, // 1: him.Req.Type:type_name -> him.MsgType
	3, // 2: him.Req.Receiver:type_name -> him.Receiver
	2, // 3: him.Event.Type:type_name -> him.EventType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_service_im_gateway_protocol_long_proto_init() }
func file_service_service_im_gateway_protocol_long_proto_init() {
	if File_service_service_im_gateway_protocol_long_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_service_im_gateway_protocol_long_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_service_im_gateway_protocol_long_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_service_im_gateway_protocol_long_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_service_im_gateway_protocol_long_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_service_im_gateway_protocol_long_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_service_im_gateway_protocol_long_proto_goTypes,
		DependencyIndexes: file_service_service_im_gateway_protocol_long_proto_depIdxs,
		EnumInfos:         file_service_service_im_gateway_protocol_long_proto_enumTypes,
		MessageInfos:      file_service_service_im_gateway_protocol_long_proto_msgTypes,
	}.Build()
	File_service_service_im_gateway_protocol_long_proto = out.File
	file_service_service_im_gateway_protocol_long_proto_rawDesc = nil
	file_service_service_im_gateway_protocol_long_proto_goTypes = nil
	file_service_service_im_gateway_protocol_long_proto_depIdxs = nil
}
