// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.0
// source: api/friend/friend.proto

package friend

import (
	constant "github.com/xiaohuashifu/him/api/constant"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加好友申请状态
type AddFriendApplication_Status int32

const (
	AddFriendApplication_STATUS_UNSPECIFIED  AddFriendApplication_Status = 0 // 未知
	AddFriendApplication_STATUS_WAIT_CONFIRM AddFriendApplication_Status = 1 // 等待确认
	AddFriendApplication_STATUS_REJECT       AddFriendApplication_Status = 2 // 拒绝
	AddFriendApplication_STATUS_ACCEPT       AddFriendApplication_Status = 3 // 接受
	AddFriendApplication_STATUS_EXPIRE       AddFriendApplication_Status = 4 // 过期
)

// Enum value maps for AddFriendApplication_Status.
var (
	AddFriendApplication_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_WAIT_CONFIRM",
		2: "STATUS_REJECT",
		3: "STATUS_ACCEPT",
		4: "STATUS_EXPIRE",
	}
	AddFriendApplication_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_WAIT_CONFIRM": 1,
		"STATUS_REJECT":       2,
		"STATUS_ACCEPT":       3,
		"STATUS_EXPIRE":       4,
	}
)

func (x AddFriendApplication_Status) Enum() *AddFriendApplication_Status {
	p := new(AddFriendApplication_Status)
	*p = x
	return p
}

func (x AddFriendApplication_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddFriendApplication_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_friend_friend_proto_enumTypes[0].Descriptor()
}

func (AddFriendApplication_Status) Type() protoreflect.EnumType {
	return &file_api_friend_friend_proto_enumTypes[0]
}

func (x AddFriendApplication_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddFriendApplication_Status.Descriptor instead.
func (AddFriendApplication_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{7, 0}
}

// 好友信息
type FriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId    uint64          `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`          // 好友编号
	NickName    string          `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`           // 昵称
	Username    string          `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                           // 用户名
	Avatar      string          `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`                               // 头像
	Gender      constant.Gender `protobuf:"varint,5,opt,name=gender,proto3,enum=constant.Gender" json:"gender,omitempty"`         // 性别
	Remark      string          `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`                               // 备注
	Description string          `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                     // 描述
	IsDisturb   bool            `protobuf:"varint,8,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb,omitempty"`       // 是否免打扰
	IsBlacklist bool            `protobuf:"varint,9,opt,name=is_blacklist,json=isBlacklist,proto3" json:"is_blacklist,omitempty"` // 是否黑名单
	IsTop       bool            `protobuf:"varint,10,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                  // 是否置顶
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{0}
}

func (x *FriendInfo) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *FriendInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FriendInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendInfo) GetGender() constant.Gender {
	if x != nil {
		return x.Gender
	}
	return constant.Gender_GENDER_UNSPECIFIED
}

func (x *FriendInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FriendInfo) GetIsDisturb() bool {
	if x != nil {
		return x.IsDisturb
	}
	return false
}

func (x *FriendInfo) GetIsBlacklist() bool {
	if x != nil {
		return x.IsBlacklist
	}
	return false
}

func (x *FriendInfo) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

// 获取好友信息请求
type GetFriendInfosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户编号
	// Types that are assignable to Condition:
	//	*GetFriendInfosReq_Username
	//	*GetFriendInfosReq_FriendId
	//	*GetFriendInfosReq_All
	Condition isGetFriendInfosReq_Condition `protobuf_oneof:"condition"`
}

func (x *GetFriendInfosReq) Reset() {
	*x = GetFriendInfosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendInfosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendInfosReq) ProtoMessage() {}

func (x *GetFriendInfosReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendInfosReq.ProtoReflect.Descriptor instead.
func (*GetFriendInfosReq) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{1}
}

func (x *GetFriendInfosReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (m *GetFriendInfosReq) GetCondition() isGetFriendInfosReq_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *GetFriendInfosReq) GetUsername() string {
	if x, ok := x.GetCondition().(*GetFriendInfosReq_Username); ok {
		return x.Username
	}
	return ""
}

func (x *GetFriendInfosReq) GetFriendId() uint64 {
	if x, ok := x.GetCondition().(*GetFriendInfosReq_FriendId); ok {
		return x.FriendId
	}
	return 0
}

func (x *GetFriendInfosReq) GetAll() bool {
	if x, ok := x.GetCondition().(*GetFriendInfosReq_All); ok {
		return x.All
	}
	return false
}

type isGetFriendInfosReq_Condition interface {
	isGetFriendInfosReq_Condition()
}

type GetFriendInfosReq_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"` // 好友用户名
}

type GetFriendInfosReq_FriendId struct {
	FriendId uint64 `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3,oneof"` // 好友编号
}

type GetFriendInfosReq_All struct {
	All bool `protobuf:"varint,4,opt,name=all,proto3,oneof"` // 全部
}

func (*GetFriendInfosReq_Username) isGetFriendInfosReq_Condition() {}

func (*GetFriendInfosReq_FriendId) isGetFriendInfosReq_Condition() {}

func (*GetFriendInfosReq_All) isGetFriendInfosReq_Condition() {}

// 获取好友信息响应
type GetFriendInfosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendInfos []*FriendInfo `protobuf:"bytes,1,rep,name=friend_infos,json=friendInfos,proto3" json:"friend_infos,omitempty"` // 好友信息列表
}

func (x *GetFriendInfosResp) Reset() {
	*x = GetFriendInfosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFriendInfosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendInfosResp) ProtoMessage() {}

func (x *GetFriendInfosResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendInfosResp.ProtoReflect.Descriptor instead.
func (*GetFriendInfosResp) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{2}
}

func (x *GetFriendInfosResp) GetFriendInfos() []*FriendInfo {
	if x != nil {
		return x.FriendInfos
	}
	return nil
}

// 更新好友信息请求
type UpdateFriendInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户编号
	FriendId uint64 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友编号
	// Types that are assignable to Action:
	//	*UpdateFriendInfoReq_IsDisturb
	//	*UpdateFriendInfoReq_IsBlacklist
	Action isUpdateFriendInfoReq_Action `protobuf_oneof:"action"`
}

func (x *UpdateFriendInfoReq) Reset() {
	*x = UpdateFriendInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFriendInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendInfoReq) ProtoMessage() {}

func (x *UpdateFriendInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateFriendInfoReq) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFriendInfoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateFriendInfoReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (m *UpdateFriendInfoReq) GetAction() isUpdateFriendInfoReq_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *UpdateFriendInfoReq) GetIsDisturb() bool {
	if x, ok := x.GetAction().(*UpdateFriendInfoReq_IsDisturb); ok {
		return x.IsDisturb
	}
	return false
}

func (x *UpdateFriendInfoReq) GetIsBlacklist() bool {
	if x, ok := x.GetAction().(*UpdateFriendInfoReq_IsBlacklist); ok {
		return x.IsBlacklist
	}
	return false
}

type isUpdateFriendInfoReq_Action interface {
	isUpdateFriendInfoReq_Action()
}

type UpdateFriendInfoReq_IsDisturb struct {
	IsDisturb bool `protobuf:"varint,3,opt,name=is_disturb,json=isDisturb,proto3,oneof"` // 是否免打扰
}

type UpdateFriendInfoReq_IsBlacklist struct {
	IsBlacklist bool `protobuf:"varint,4,opt,name=is_blacklist,json=isBlacklist,proto3,oneof"` // 是否黑名单
}

func (*UpdateFriendInfoReq_IsDisturb) isUpdateFriendInfoReq_Action() {}

func (*UpdateFriendInfoReq_IsBlacklist) isUpdateFriendInfoReq_Action() {}

// 更新好友信息响应
type UpdateFriendInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFriendInfoResp) Reset() {
	*x = UpdateFriendInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFriendInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendInfoResp) ProtoMessage() {}

func (x *UpdateFriendInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateFriendInfoResp) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{4}
}

// 删除好友请求
type DeleteFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户编号
	FriendId uint64 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友编号
}

func (x *DeleteFriendReq) Reset() {
	*x = DeleteFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendReq) ProtoMessage() {}

func (x *DeleteFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendReq.ProtoReflect.Descriptor instead.
func (*DeleteFriendReq) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFriendReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFriendReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 删除好友响应
type DeleteFriendResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFriendResp) Reset() {
	*x = DeleteFriendResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResp) ProtoMessage() {}

func (x *DeleteFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResp.ProtoReflect.Descriptor instead.
func (*DeleteFriendResp) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{6}
}

// 添加好友申请
type AddFriendApplication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplicationId uint64                      `protobuf:"varint,1,opt,name=add_friend_application_id,json=addFriendApplicationId,proto3" json:"add_friend_application_id,omitempty"` // 添加好友申请编号
	ApplicantId            uint64                      `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`                                      // 申请者用户编号
	FriendId               uint64                      `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`                                               // 好友编号
	ApplicationMsg         string                      `protobuf:"bytes,4,opt,name=application_msg,json=applicationMsg,proto3" json:"application_msg,omitempty"`                              // 申请消息
	FriendReply            string                      `protobuf:"bytes,5,opt,name=friend_reply,json=friendReply,proto3" json:"friend_reply,omitempty"`                                       // 好友回复
	Status                 AddFriendApplication_Status `protobuf:"varint,6,opt,name=status,proto3,enum=friend.AddFriendApplication_Status" json:"status,omitempty"`                           // 申请状态
	ApplicationTime        uint64                      `protobuf:"varint,7,opt,name=application_time,json=applicationTime,proto3" json:"application_time,omitempty"`                          // 申请时间
}

func (x *AddFriendApplication) Reset() {
	*x = AddFriendApplication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendApplication) ProtoMessage() {}

func (x *AddFriendApplication) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendApplication.ProtoReflect.Descriptor instead.
func (*AddFriendApplication) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{7}
}

func (x *AddFriendApplication) GetAddFriendApplicationId() uint64 {
	if x != nil {
		return x.AddFriendApplicationId
	}
	return 0
}

func (x *AddFriendApplication) GetApplicantId() uint64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *AddFriendApplication) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *AddFriendApplication) GetApplicationMsg() string {
	if x != nil {
		return x.ApplicationMsg
	}
	return ""
}

func (x *AddFriendApplication) GetFriendReply() string {
	if x != nil {
		return x.FriendReply
	}
	return ""
}

func (x *AddFriendApplication) GetStatus() AddFriendApplication_Status {
	if x != nil {
		return x.Status
	}
	return AddFriendApplication_STATUS_UNSPECIFIED
}

func (x *AddFriendApplication) GetApplicationTime() uint64 {
	if x != nil {
		return x.ApplicationTime
	}
	return 0
}

// 获取添加好友申请请求
type GetAddFriendApplicationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId                     uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                   // 用户编号
	LastAddFriendApplicationId uint64 `protobuf:"varint,2,opt,name=last_add_friend_application_id,json=lastAddFriendApplicationId,proto3" json:"last_add_friend_application_id,omitempty"` // 最后一个添加好友请求的编号（因为是反过来排序的）
	Size                       uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                                                                                     // 多少条
}

func (x *GetAddFriendApplicationsReq) Reset() {
	*x = GetAddFriendApplicationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddFriendApplicationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddFriendApplicationsReq) ProtoMessage() {}

func (x *GetAddFriendApplicationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddFriendApplicationsReq.ProtoReflect.Descriptor instead.
func (*GetAddFriendApplicationsReq) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{8}
}

func (x *GetAddFriendApplicationsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAddFriendApplicationsReq) GetLastAddFriendApplicationId() uint64 {
	if x != nil {
		return x.LastAddFriendApplicationId
	}
	return 0
}

func (x *GetAddFriendApplicationsReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 获取添加好友申请响应
type GetAddFriendApplicationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplications []*AddFriendApplication `protobuf:"bytes,1,rep,name=add_friend_applications,json=addFriendApplications,proto3" json:"add_friend_applications,omitempty"` // 添加好友申请
}

func (x *GetAddFriendApplicationsResp) Reset() {
	*x = GetAddFriendApplicationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddFriendApplicationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddFriendApplicationsResp) ProtoMessage() {}

func (x *GetAddFriendApplicationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddFriendApplicationsResp.ProtoReflect.Descriptor instead.
func (*GetAddFriendApplicationsResp) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{9}
}

func (x *GetAddFriendApplicationsResp) GetAddFriendApplications() []*AddFriendApplication {
	if x != nil {
		return x.AddFriendApplications
	}
	return nil
}

// 添加好友申请请求
type AddFriendApplicationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicantId    uint64 `protobuf:"varint,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`         // 申请人编号
	FriendId       uint64 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`                  // 好友编号
	ApplicationMsg string `protobuf:"bytes,3,opt,name=application_msg,json=applicationMsg,proto3" json:"application_msg,omitempty"` // 申请消息
}

func (x *AddFriendApplicationReq) Reset() {
	*x = AddFriendApplicationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendApplicationReq) ProtoMessage() {}

func (x *AddFriendApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendApplicationReq.ProtoReflect.Descriptor instead.
func (*AddFriendApplicationReq) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{10}
}

func (x *AddFriendApplicationReq) GetApplicantId() uint64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *AddFriendApplicationReq) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *AddFriendApplicationReq) GetApplicationMsg() string {
	if x != nil {
		return x.ApplicationMsg
	}
	return ""
}

// 添加好友申请响应
type AddFriendApplicationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplicationId uint64 `protobuf:"varint,1,opt,name=add_friend_application_id,json=addFriendApplicationId,proto3" json:"add_friend_application_id,omitempty"` // 添加好友申请编号
}

func (x *AddFriendApplicationResp) Reset() {
	*x = AddFriendApplicationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendApplicationResp) ProtoMessage() {}

func (x *AddFriendApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendApplicationResp.ProtoReflect.Descriptor instead.
func (*AddFriendApplicationResp) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{11}
}

func (x *AddFriendApplicationResp) GetAddFriendApplicationId() uint64 {
	if x != nil {
		return x.AddFriendApplicationId
	}
	return 0
}

// 更新添加好友申请请求
type UpdateAddFriendApplicationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplicationId uint64 `protobuf:"varint,1,opt,name=add_friend_application_id,json=addFriendApplicationId,proto3" json:"add_friend_application_id,omitempty"` // 添加好友申请编号
	// Types that are assignable to Action:
	//	*UpdateAddFriendApplicationReq_ApplicationMsg
	//	*UpdateAddFriendApplicationReq_FriendReply
	//	*UpdateAddFriendApplicationReq_Accept
	//	*UpdateAddFriendApplicationReq_Reject
	Action isUpdateAddFriendApplicationReq_Action `protobuf_oneof:"action"`
}

func (x *UpdateAddFriendApplicationReq) Reset() {
	*x = UpdateAddFriendApplicationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddFriendApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddFriendApplicationReq) ProtoMessage() {}

func (x *UpdateAddFriendApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddFriendApplicationReq.ProtoReflect.Descriptor instead.
func (*UpdateAddFriendApplicationReq) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateAddFriendApplicationReq) GetAddFriendApplicationId() uint64 {
	if x != nil {
		return x.AddFriendApplicationId
	}
	return 0
}

func (m *UpdateAddFriendApplicationReq) GetAction() isUpdateAddFriendApplicationReq_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *UpdateAddFriendApplicationReq) GetApplicationMsg() string {
	if x, ok := x.GetAction().(*UpdateAddFriendApplicationReq_ApplicationMsg); ok {
		return x.ApplicationMsg
	}
	return ""
}

func (x *UpdateAddFriendApplicationReq) GetFriendReply() string {
	if x, ok := x.GetAction().(*UpdateAddFriendApplicationReq_FriendReply); ok {
		return x.FriendReply
	}
	return ""
}

func (x *UpdateAddFriendApplicationReq) GetAccept() bool {
	if x, ok := x.GetAction().(*UpdateAddFriendApplicationReq_Accept); ok {
		return x.Accept
	}
	return false
}

func (x *UpdateAddFriendApplicationReq) GetReject() bool {
	if x, ok := x.GetAction().(*UpdateAddFriendApplicationReq_Reject); ok {
		return x.Reject
	}
	return false
}

type isUpdateAddFriendApplicationReq_Action interface {
	isUpdateAddFriendApplicationReq_Action()
}

type UpdateAddFriendApplicationReq_ApplicationMsg struct {
	ApplicationMsg string `protobuf:"bytes,2,opt,name=application_msg,json=applicationMsg,proto3,oneof"` // 申请消息
}

type UpdateAddFriendApplicationReq_FriendReply struct {
	FriendReply string `protobuf:"bytes,3,opt,name=friend_reply,json=friendReply,proto3,oneof"` // 好友回复
}

type UpdateAddFriendApplicationReq_Accept struct {
	Accept bool `protobuf:"varint,4,opt,name=accept,proto3,oneof"` // 接受
}

type UpdateAddFriendApplicationReq_Reject struct {
	Reject bool `protobuf:"varint,5,opt,name=reject,proto3,oneof"` // 拒绝
}

func (*UpdateAddFriendApplicationReq_ApplicationMsg) isUpdateAddFriendApplicationReq_Action() {}

func (*UpdateAddFriendApplicationReq_FriendReply) isUpdateAddFriendApplicationReq_Action() {}

func (*UpdateAddFriendApplicationReq_Accept) isUpdateAddFriendApplicationReq_Action() {}

func (*UpdateAddFriendApplicationReq_Reject) isUpdateAddFriendApplicationReq_Action() {}

// 更新添加好友申请响应
type UpdateAddFriendApplicationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAddFriendApplicationResp) Reset() {
	*x = UpdateAddFriendApplicationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAddFriendApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddFriendApplicationResp) ProtoMessage() {}

func (x *UpdateAddFriendApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddFriendApplicationResp.ProtoReflect.Descriptor instead.
func (*UpdateAddFriendApplicationResp) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{13}
}

// @存储模型
// 添加好友申请
// 这里在检索的时候根据ApplicantID和FriendID查询自己的所有申请
// 根据AddFriendApplicationID逆序排序
type AddFriendApplicationStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddFriendApplication *AddFriendApplication `protobuf:"bytes,1,opt,name=add_friend_application,json=addFriendApplication,proto3" json:"add_friend_application,omitempty"` // 申请
}

func (x *AddFriendApplicationStore) Reset() {
	*x = AddFriendApplicationStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendApplicationStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendApplicationStore) ProtoMessage() {}

func (x *AddFriendApplicationStore) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendApplicationStore.ProtoReflect.Descriptor instead.
func (*AddFriendApplicationStore) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{14}
}

func (x *AddFriendApplicationStore) GetAddFriendApplication() *AddFriendApplication {
	if x != nil {
		return x.AddFriendApplication
	}
	return nil
}

// @存储模型
// 好友
type FriendStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户编号
	FriendId    uint64 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`            // 好友编号
	Remark      string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`                                 // 备注
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                       // 描述
	IsIgnoreMsg bool   `protobuf:"varint,5,opt,name=is_ignore_msg,json=isIgnoreMsg,proto3" json:"is_ignore_msg,omitempty"` // 是否忽略对方的消息
	IsBlacklist bool   `protobuf:"varint,6,opt,name=is_blacklist,json=isBlacklist,proto3" json:"is_blacklist,omitempty"`   // 是否黑名单
	IsTop       bool   `protobuf:"varint,7,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                     // 是否置顶
	CreatedAt   uint64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // 建立时间
	UpdatedAt   uint64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`         // 修改时间
}

func (x *FriendStore) Reset() {
	*x = FriendStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_friend_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendStore) ProtoMessage() {}

func (x *FriendStore) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_friend_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendStore.ProtoReflect.Descriptor instead.
func (*FriendStore) Descriptor() ([]byte, []int) {
	return file_api_friend_friend_proto_rawDescGZIP(), []int{15}
}

func (x *FriendStore) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendStore) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendStore) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendStore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FriendStore) GetIsIgnoreMsg() bool {
	if x != nil {
		return x.IsIgnoreMsg
	}
	return false
}

func (x *FriendStore) GetIsBlacklist() bool {
	if x != nil {
		return x.IsBlacklist
	}
	return false
}

func (x *FriendStore) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *FriendStore) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FriendStore) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_api_friend_friend_proto protoreflect.FileDescriptor

var file_api_friend_friend_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2f, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7,
	0x02, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69,
	0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x28, 0x0a, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x75, 0x72, 0x62, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x69, 0x73, 0x74, 0x75, 0x72, 0x62, 0x12, 0x21,
	0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x74, 0x6f, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x69, 0x73, 0x54, 0x6f, 0x70, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0c, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x75, 0x72, 0x62, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x69, 0x73, 0x44, 0x69, 0x73, 0x74, 0x75, 0x72,
	0x62, 0x12, 0x23, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x73, 0x42, 0x6c, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x47, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49,
	0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0xb9, 0x03, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39,
	0x0a, 0x19, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x16, 0x61, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x73, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x72, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x5f, 0x43,
	0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x03, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x10,
	0x04, 0x22, 0x8e, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x1e, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x1a, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0x74, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x54, 0x0a, 0x17, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x41, 0x64, 0x64,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x15, 0x61, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x17, 0x41, 0x64, 0x64,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x22, 0x55, 0x0a,
	0x18, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x19, 0x61, 0x64, 0x64,
	0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x61, 0x64,
	0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0xe8, 0x01, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x19, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x61, 0x64, 0x64, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x23, 0x0a, 0x0c,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x72,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x72,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x20, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x6f, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x52,
	0x0a, 0x16, 0x61, 0x64, 0x64, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x61, 0x64,
	0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x99, 0x02, 0x0a, 0x0b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x49, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x62, 0x6c, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f,
	0x74, 0x6f, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x54, 0x6f, 0x70,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x99,
	0x04, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x47, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x12, 0x19, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x2e,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x17, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x65, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x23, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x59, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6b, 0x0a,
	0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x26, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x61, 0x6f, 0x68, 0x75, 0x61,
	0x73, 0x68, 0x69, 0x66, 0x75, 0x2f, 0x68, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_friend_friend_proto_rawDescOnce sync.Once
	file_api_friend_friend_proto_rawDescData = file_api_friend_friend_proto_rawDesc
)

func file_api_friend_friend_proto_rawDescGZIP() []byte {
	file_api_friend_friend_proto_rawDescOnce.Do(func() {
		file_api_friend_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_friend_friend_proto_rawDescData)
	})
	return file_api_friend_friend_proto_rawDescData
}

var file_api_friend_friend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_friend_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_friend_friend_proto_goTypes = []interface{}{
	(AddFriendApplication_Status)(0),       // 0: friend.AddFriendApplication.Status
	(*FriendInfo)(nil),                     // 1: friend.FriendInfo
	(*GetFriendInfosReq)(nil),              // 2: friend.GetFriendInfosReq
	(*GetFriendInfosResp)(nil),             // 3: friend.GetFriendInfosResp
	(*UpdateFriendInfoReq)(nil),            // 4: friend.UpdateFriendInfoReq
	(*UpdateFriendInfoResp)(nil),           // 5: friend.UpdateFriendInfoResp
	(*DeleteFriendReq)(nil),                // 6: friend.DeleteFriendReq
	(*DeleteFriendResp)(nil),               // 7: friend.DeleteFriendResp
	(*AddFriendApplication)(nil),           // 8: friend.AddFriendApplication
	(*GetAddFriendApplicationsReq)(nil),    // 9: friend.GetAddFriendApplicationsReq
	(*GetAddFriendApplicationsResp)(nil),   // 10: friend.GetAddFriendApplicationsResp
	(*AddFriendApplicationReq)(nil),        // 11: friend.AddFriendApplicationReq
	(*AddFriendApplicationResp)(nil),       // 12: friend.AddFriendApplicationResp
	(*UpdateAddFriendApplicationReq)(nil),  // 13: friend.UpdateAddFriendApplicationReq
	(*UpdateAddFriendApplicationResp)(nil), // 14: friend.UpdateAddFriendApplicationResp
	(*AddFriendApplicationStore)(nil),      // 15: friend.AddFriendApplicationStore
	(*FriendStore)(nil),                    // 16: friend.FriendStore
	(constant.Gender)(0),                   // 17: constant.Gender
}
var file_api_friend_friend_proto_depIdxs = []int32{
	17, // 0: friend.FriendInfo.gender:type_name -> constant.Gender
	1,  // 1: friend.GetFriendInfosResp.friend_infos:type_name -> friend.FriendInfo
	0,  // 2: friend.AddFriendApplication.status:type_name -> friend.AddFriendApplication.Status
	8,  // 3: friend.GetAddFriendApplicationsResp.add_friend_applications:type_name -> friend.AddFriendApplication
	8,  // 4: friend.AddFriendApplicationStore.add_friend_application:type_name -> friend.AddFriendApplication
	2,  // 5: friend.FriendService.GetFriendInfos:input_type -> friend.GetFriendInfosReq
	4,  // 6: friend.FriendService.UpdateFriendInfo:input_type -> friend.UpdateFriendInfoReq
	6,  // 7: friend.FriendService.DeleteFriend:input_type -> friend.DeleteFriendReq
	9,  // 8: friend.FriendService.GetAddFriendApplications:input_type -> friend.GetAddFriendApplicationsReq
	11, // 9: friend.FriendService.AddFriendApplication:input_type -> friend.AddFriendApplicationReq
	13, // 10: friend.FriendService.UpdateAddFriendApplication:input_type -> friend.UpdateAddFriendApplicationReq
	3,  // 11: friend.FriendService.GetFriendInfos:output_type -> friend.GetFriendInfosResp
	5,  // 12: friend.FriendService.UpdateFriendInfo:output_type -> friend.UpdateFriendInfoResp
	7,  // 13: friend.FriendService.DeleteFriend:output_type -> friend.DeleteFriendResp
	10, // 14: friend.FriendService.GetAddFriendApplications:output_type -> friend.GetAddFriendApplicationsResp
	12, // 15: friend.FriendService.AddFriendApplication:output_type -> friend.AddFriendApplicationResp
	14, // 16: friend.FriendService.UpdateAddFriendApplication:output_type -> friend.UpdateAddFriendApplicationResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_friend_friend_proto_init() }
func file_api_friend_friend_proto_init() {
	if File_api_friend_friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_friend_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendInfosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFriendInfosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFriendInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFriendInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFriendResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendApplication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddFriendApplicationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddFriendApplicationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendApplicationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendApplicationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddFriendApplicationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAddFriendApplicationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendApplicationStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_friend_friend_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_friend_friend_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetFriendInfosReq_Username)(nil),
		(*GetFriendInfosReq_FriendId)(nil),
		(*GetFriendInfosReq_All)(nil),
	}
	file_api_friend_friend_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*UpdateFriendInfoReq_IsDisturb)(nil),
		(*UpdateFriendInfoReq_IsBlacklist)(nil),
	}
	file_api_friend_friend_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*UpdateAddFriendApplicationReq_ApplicationMsg)(nil),
		(*UpdateAddFriendApplicationReq_FriendReply)(nil),
		(*UpdateAddFriendApplicationReq_Accept)(nil),
		(*UpdateAddFriendApplicationReq_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_friend_friend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_friend_friend_proto_goTypes,
		DependencyIndexes: file_api_friend_friend_proto_depIdxs,
		EnumInfos:         file_api_friend_friend_proto_enumTypes,
		MessageInfos:      file_api_friend_friend_proto_msgTypes,
	}.Build()
	File_api_friend_friend_proto = out.File
	file_api_friend_friend_proto_rawDesc = nil
	file_api_friend_friend_proto_goTypes = nil
	file_api_friend_friend_proto_depIdxs = nil
}
