// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.0
// source: api/authnz/authz/mq/mq.proto

package mq

import (
	authnz "github.com/xiaohuashifu/him/api/authnz"
	authz "github.com/xiaohuashifu/him/api/authnz/authz"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MQ授权组
type AuthzGroup int32

const (
	AuthzGroup_AUTHZ_GROUP_UNSPECIFIED AuthzGroup = 0 // 未知
	AuthzGroup_AUTHZ_GROUP_PRODUCER    AuthzGroup = 1 // 生产者
	AuthzGroup_AUTHZ_GROUP_CONSUMER    AuthzGroup = 2 // 消费者
)

// Enum value maps for AuthzGroup.
var (
	AuthzGroup_name = map[int32]string{
		0: "AUTHZ_GROUP_UNSPECIFIED",
		1: "AUTHZ_GROUP_PRODUCER",
		2: "AUTHZ_GROUP_CONSUMER",
	}
	AuthzGroup_value = map[string]int32{
		"AUTHZ_GROUP_UNSPECIFIED": 0,
		"AUTHZ_GROUP_PRODUCER":    1,
		"AUTHZ_GROUP_CONSUMER":    2,
	}
)

func (x AuthzGroup) Enum() *AuthzGroup {
	p := new(AuthzGroup)
	*p = x
	return p
}

func (x AuthzGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthzGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_api_authnz_authz_mq_mq_proto_enumTypes[0].Descriptor()
}

func (AuthzGroup) Type() protoreflect.EnumType {
	return &file_api_authnz_authz_mq_mq_proto_enumTypes[0]
}

func (x AuthzGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthzGroup.Descriptor instead.
func (AuthzGroup) EnumDescriptor() ([]byte, []int) {
	return file_api_authnz_authz_mq_mq_proto_rawDescGZIP(), []int{0}
}

// MQ授权Tag
type AuthzTag int32

const (
	AuthzTag_AUTHZ_TAG_UNSPECIFIED  AuthzTag = 0 // 未知
	AuthzTag_AUTHZ_TAG_LOGIN_EVENT  AuthzTag = 1 // 登录事件
	AuthzTag_AUTHZ_TAG_LOGOUT_EVENT AuthzTag = 2 // 退出登录事件
)

// Enum value maps for AuthzTag.
var (
	AuthzTag_name = map[int32]string{
		0: "AUTHZ_TAG_UNSPECIFIED",
		1: "AUTHZ_TAG_LOGIN_EVENT",
		2: "AUTHZ_TAG_LOGOUT_EVENT",
	}
	AuthzTag_value = map[string]int32{
		"AUTHZ_TAG_UNSPECIFIED":  0,
		"AUTHZ_TAG_LOGIN_EVENT":  1,
		"AUTHZ_TAG_LOGOUT_EVENT": 2,
	}
)

func (x AuthzTag) Enum() *AuthzTag {
	p := new(AuthzTag)
	*p = x
	return p
}

func (x AuthzTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthzTag) Descriptor() protoreflect.EnumDescriptor {
	return file_api_authnz_authz_mq_mq_proto_enumTypes[1].Descriptor()
}

func (AuthzTag) Type() protoreflect.EnumType {
	return &file_api_authnz_authz_mq_mq_proto_enumTypes[1]
}

func (x AuthzTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthzTag.Descriptor instead.
func (AuthzTag) EnumDescriptor() ([]byte, []int) {
	return file_api_authnz_authz_mq_mq_proto_rawDescGZIP(), []int{1}
}

// 登录事件
type LoginEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64          `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                      // 用户编号
	UserType  authnz.UserType `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=authnz.UserType" json:"user_type,omitempty"`           // 用户类型
	LoginType authz.LoginType `protobuf:"varint,3,opt,name=login_type,json=loginType,proto3,enum=authnz.authz.LoginType" json:"login_type,omitempty"` // 登录类型
	LoginTime uint64          `protobuf:"varint,4,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`                             // 登录时间
}

func (x *LoginEvent) Reset() {
	*x = LoginEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_mq_mq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEvent) ProtoMessage() {}

func (x *LoginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_mq_mq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEvent.ProtoReflect.Descriptor instead.
func (*LoginEvent) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_mq_mq_proto_rawDescGZIP(), []int{0}
}

func (x *LoginEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginEvent) GetUserType() authnz.UserType {
	if x != nil {
		return x.UserType
	}
	return authnz.UserType_USER_TYPE_UNSPECIFIED
}

func (x *LoginEvent) GetLoginType() authz.LoginType {
	if x != nil {
		return x.LoginType
	}
	return authz.LoginType_LOGIN_TYPE_UNSPECIFIED
}

func (x *LoginEvent) GetLoginTime() uint64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

// 退出登录事件
type LogoutEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户编号
	LogoutTime uint64 `protobuf:"varint,2,opt,name=logout_time,json=logoutTime,proto3" json:"logout_time,omitempty"` // 退出登录时间
}

func (x *LogoutEvent) Reset() {
	*x = LogoutEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_mq_mq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutEvent) ProtoMessage() {}

func (x *LogoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_mq_mq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutEvent.ProtoReflect.Descriptor instead.
func (*LogoutEvent) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_mq_mq_proto_rawDescGZIP(), []int{1}
}

func (x *LogoutEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LogoutEvent) GetLogoutTime() uint64 {
	if x != nil {
		return x.LogoutTime
	}
	return 0
}

var File_api_authnz_authz_mq_mq_proto protoreflect.FileDescriptor

var file_api_authnz_authz_mq_mq_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2f, 0x6d, 0x71, 0x2f, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x6d, 0x71, 0x1a,
	0x1c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x7a, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a,
	0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x5d, 0x0a,
	0x0a, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1b, 0x0a, 0x17, 0x41,
	0x55, 0x54, 0x48, 0x5a, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x55, 0x54, 0x48,
	0x5a, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x55, 0x54, 0x48, 0x5a, 0x5f, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x5c, 0x0a, 0x08,
	0x41, 0x75, 0x74, 0x68, 0x7a, 0x54, 0x61, 0x67, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x55, 0x54, 0x48,
	0x5a, 0x5f, 0x54, 0x41, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x55, 0x54, 0x48, 0x5a, 0x5f, 0x54, 0x41, 0x47,
	0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x1a,
	0x0a, 0x16, 0x41, 0x55, 0x54, 0x48, 0x5a, 0x5f, 0x54, 0x41, 0x47, 0x5f, 0x4c, 0x4f, 0x47, 0x4f,
	0x55, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x61, 0x6f, 0x68, 0x75, 0x61,
	0x73, 0x68, 0x69, 0x66, 0x75, 0x2f, 0x68, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x6e, 0x7a, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2f, 0x6d, 0x71, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_authnz_authz_mq_mq_proto_rawDescOnce sync.Once
	file_api_authnz_authz_mq_mq_proto_rawDescData = file_api_authnz_authz_mq_mq_proto_rawDesc
)

func file_api_authnz_authz_mq_mq_proto_rawDescGZIP() []byte {
	file_api_authnz_authz_mq_mq_proto_rawDescOnce.Do(func() {
		file_api_authnz_authz_mq_mq_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_authnz_authz_mq_mq_proto_rawDescData)
	})
	return file_api_authnz_authz_mq_mq_proto_rawDescData
}

var file_api_authnz_authz_mq_mq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_authnz_authz_mq_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_authnz_authz_mq_mq_proto_goTypes = []interface{}{
	(AuthzGroup)(0),      // 0: authnz.authz.mq.AuthzGroup
	(AuthzTag)(0),        // 1: authnz.authz.mq.AuthzTag
	(*LoginEvent)(nil),   // 2: authnz.authz.mq.LoginEvent
	(*LogoutEvent)(nil),  // 3: authnz.authz.mq.LogoutEvent
	(authnz.UserType)(0), // 4: authnz.UserType
	(authz.LoginType)(0), // 5: authnz.authz.LoginType
}
var file_api_authnz_authz_mq_mq_proto_depIdxs = []int32{
	4, // 0: authnz.authz.mq.LoginEvent.user_type:type_name -> authnz.UserType
	5, // 1: authnz.authz.mq.LoginEvent.login_type:type_name -> authnz.authz.LoginType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_authnz_authz_mq_mq_proto_init() }
func file_api_authnz_authz_mq_mq_proto_init() {
	if File_api_authnz_authz_mq_mq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_authnz_authz_mq_mq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_mq_mq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_authnz_authz_mq_mq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_authnz_authz_mq_mq_proto_goTypes,
		DependencyIndexes: file_api_authnz_authz_mq_mq_proto_depIdxs,
		EnumInfos:         file_api_authnz_authz_mq_mq_proto_enumTypes,
		MessageInfos:      file_api_authnz_authz_mq_mq_proto_msgTypes,
	}.Build()
	File_api_authnz_authz_mq_mq_proto = out.File
	file_api_authnz_authz_mq_mq_proto_rawDesc = nil
	file_api_authnz_authz_mq_mq_proto_goTypes = nil
	file_api_authnz_authz_mq_mq_proto_depIdxs = nil
}
