// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: api/session/session.proto

package session

import (
	constant "github.com/xiaohuashifu/him/api/constant"
	user "github.com/xiaohuashifu/him/api/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取会话请求
type GetSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // 凭证
}

func (x *GetSessionReq) Reset() {
	*x = GetSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_session_session_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionReq) ProtoMessage() {}

func (x *GetSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_session_session_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionReq.ProtoReflect.Descriptor instead.
func (*GetSessionReq) Descriptor() ([]byte, []int) {
	return file_api_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取会话响应
type GetSessionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"` // 会话
}

func (x *GetSessionRsp) Reset() {
	*x = GetSessionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_session_session_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSessionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRsp) ProtoMessage() {}

func (x *GetSessionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_session_session_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRsp.ProtoReflect.Descriptor instead.
func (*GetSessionRsp) Descriptor() ([]byte, []int) {
	return file_api_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionRsp) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

// Session 会话
type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64            `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`                            // 用户编号
	UserType user.UserType     `protobuf:"varint,2,opt,name=UserType,proto3,enum=user.UserType" json:"UserType,omitempty"`     // 用户类型
	Terminal constant.Terminal `protobuf:"varint,3,opt,name=Terminal,proto3,enum=constant.Terminal" json:"Terminal,omitempty"` // 终端
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_session_session_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_session_session_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_session_session_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Session) GetUserType() user.UserType {
	if x != nil {
		return x.UserType
	}
	return user.UserType(0)
}

func (x *Session) GetTerminal() constant.Terminal {
	if x != nil {
		return x.Terminal
	}
	return constant.Terminal(0)
}

var File_api_session_session_proto protoreflect.FileDescriptor

var file_api_session_session_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x75, 0x74,
	0x68, 0x6e, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x13, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x39, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x07,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x7d, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x54, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x61, 0x6f, 0x68, 0x75, 0x61, 0x73, 0x68, 0x69, 0x66, 0x75,
	0x2f, 0x68, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_session_session_proto_rawDescOnce sync.Once
	file_api_session_session_proto_rawDescData = file_api_session_session_proto_rawDesc
)

func file_api_session_session_proto_rawDescGZIP() []byte {
	file_api_session_session_proto_rawDescOnce.Do(func() {
		file_api_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_session_session_proto_rawDescData)
	})
	return file_api_session_session_proto_rawDescData
}

var file_api_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_session_session_proto_goTypes = []interface{}{
	(*GetSessionReq)(nil),  // 0: authn.GetSessionReq
	(*GetSessionRsp)(nil),  // 1: authn.GetSessionRsp
	(*Session)(nil),        // 2: authn.Session
	(user.UserType)(0),     // 3: user.UserType
	(constant.Terminal)(0), // 4: constant.Terminal
}
var file_api_session_session_proto_depIdxs = []int32{
	2, // 0: authn.GetSessionRsp.Session:type_name -> authn.Session
	3, // 1: authn.Session.UserType:type_name -> user.UserType
	4, // 2: authn.Session.Terminal:type_name -> constant.Terminal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_session_session_proto_init() }
func file_api_session_session_proto_init() {
	if File_api_session_session_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_session_session_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_session_session_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSessionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_session_session_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_session_session_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_session_session_proto_goTypes,
		DependencyIndexes: file_api_session_session_proto_depIdxs,
		MessageInfos:      file_api_session_session_proto_msgTypes,
	}.Build()
	File_api_session_session_proto = out.File
	file_api_session_session_proto_rawDesc = nil
	file_api_session_session_proto_goTypes = nil
	file_api_session_session_proto_depIdxs = nil
}
