// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.0
// source: api/authnz/authz/authz.proto

package authz

import (
	constant "github.com/xiaohuashifu/him/api/constant"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录类型
type LoginType int32

const (
	LoginType_LOGIN_TYPE_UNSPECIFIED LoginType = 0 // 未知
	LoginType_LOGIN_TYPE_SM_VER_CODE LoginType = 1 // 短信验证码
	LoginType_LOGIN_TYPE_PWD         LoginType = 2 // 密码
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "LOGIN_TYPE_UNSPECIFIED",
		1: "LOGIN_TYPE_SM_VER_CODE",
		2: "LOGIN_TYPE_PWD",
	}
	LoginType_value = map[string]int32{
		"LOGIN_TYPE_UNSPECIFIED": 0,
		"LOGIN_TYPE_SM_VER_CODE": 1,
		"LOGIN_TYPE_PWD":         2,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_authnz_authz_authz_proto_enumTypes[0].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_api_authnz_authz_authz_proto_enumTypes[0]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{0}
}

// 登录请求
type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Terminal constant.Terminal `protobuf:"varint,1,opt,name=terminal,proto3,enum=constant.Terminal" json:"terminal,omitempty"` // 终端
	// Types that are assignable to Content:
	//	*LoginReq_SmVerCodeContent_
	//	*LoginReq_PwdContent_
	Content isLoginReq_Content `protobuf_oneof:"content"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetTerminal() constant.Terminal {
	if x != nil {
		return x.Terminal
	}
	return constant.Terminal_TERMINAL_UNSPECIFIED
}

func (m *LoginReq) GetContent() isLoginReq_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *LoginReq) GetSmVerCodeContent() *LoginReq_SmVerCodeContent {
	if x, ok := x.GetContent().(*LoginReq_SmVerCodeContent_); ok {
		return x.SmVerCodeContent
	}
	return nil
}

func (x *LoginReq) GetPwdContent() *LoginReq_PwdContent {
	if x, ok := x.GetContent().(*LoginReq_PwdContent_); ok {
		return x.PwdContent
	}
	return nil
}

type isLoginReq_Content interface {
	isLoginReq_Content()
}

type LoginReq_SmVerCodeContent_ struct {
	SmVerCodeContent *LoginReq_SmVerCodeContent `protobuf:"bytes,2,opt,name=sm_ver_code_content,json=smVerCodeContent,proto3,oneof"`
}

type LoginReq_PwdContent_ struct {
	PwdContent *LoginReq_PwdContent `protobuf:"bytes,3,opt,name=pwd_content,json=pwdContent,proto3,oneof"`
}

func (*LoginReq_SmVerCodeContent_) isLoginReq_Content() {}

func (*LoginReq_PwdContent_) isLoginReq_Content() {}

// 登录响应
type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                  // 凭证
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户编号
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 发送短信登录验证码请求
type SendSmVerCodeForLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone    string            `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`                               // 手机号码
	Terminal constant.Terminal `protobuf:"varint,2,opt,name=terminal,proto3,enum=constant.Terminal" json:"terminal,omitempty"` // 终端
}

func (x *SendSmVerCodeForLoginReq) Reset() {
	*x = SendSmVerCodeForLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSmVerCodeForLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmVerCodeForLoginReq) ProtoMessage() {}

func (x *SendSmVerCodeForLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmVerCodeForLoginReq.ProtoReflect.Descriptor instead.
func (*SendSmVerCodeForLoginReq) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{2}
}

func (x *SendSmVerCodeForLoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendSmVerCodeForLoginReq) GetTerminal() constant.Terminal {
	if x != nil {
		return x.Terminal
	}
	return constant.Terminal_TERMINAL_UNSPECIFIED
}

// 发送短信登录验证码响应
type SendSmVerCodeForLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendSmVerCodeForLoginResp) Reset() {
	*x = SendSmVerCodeForLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSmVerCodeForLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmVerCodeForLoginResp) ProtoMessage() {}

func (x *SendSmVerCodeForLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmVerCodeForLoginResp.ProtoReflect.Descriptor instead.
func (*SendSmVerCodeForLoginResp) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{3}
}

// 更新密码请求
type UpdatePwdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 用户编号
	Pwd       string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`                                // 新密码
	SmVerCode string `protobuf:"bytes,3,opt,name=sm_ver_code,json=smVerCode,proto3" json:"sm_ver_code,omitempty"` // 短信验证码
}

func (x *UpdatePwdReq) Reset() {
	*x = UpdatePwdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePwdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePwdReq) ProtoMessage() {}

func (x *UpdatePwdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePwdReq.ProtoReflect.Descriptor instead.
func (*UpdatePwdReq) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePwdReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePwdReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *UpdatePwdReq) GetSmVerCode() string {
	if x != nil {
		return x.SmVerCode
	}
	return ""
}

// 更新密码响应
type UpdatePwdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePwdResp) Reset() {
	*x = UpdatePwdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePwdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePwdResp) ProtoMessage() {}

func (x *UpdatePwdResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePwdResp.ProtoReflect.Descriptor instead.
func (*UpdatePwdResp) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{5}
}

// 退出登录请求
type LogoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 凭证
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 退出登录响应
type LogoutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{7}
}

// 短信验证码内容
type LoginReq_SmVerCodeContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone     string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`                            // 手机号码
	SmVerCode string `protobuf:"bytes,2,opt,name=sm_ver_code,json=smVerCode,proto3" json:"sm_ver_code,omitempty"` // 短信验证码
}

func (x *LoginReq_SmVerCodeContent) Reset() {
	*x = LoginReq_SmVerCodeContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq_SmVerCodeContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq_SmVerCodeContent) ProtoMessage() {}

func (x *LoginReq_SmVerCodeContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq_SmVerCodeContent.ProtoReflect.Descriptor instead.
func (*LoginReq_SmVerCodeContent) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoginReq_SmVerCodeContent) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq_SmVerCodeContent) GetSmVerCode() string {
	if x != nil {
		return x.SmVerCode
	}
	return ""
}

// 密码内容
type LoginReq_PwdContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 账号
	Pwd     string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`         // 密码
}

func (x *LoginReq_PwdContent) Reset() {
	*x = LoginReq_PwdContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authnz_authz_authz_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq_PwdContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq_PwdContent) ProtoMessage() {}

func (x *LoginReq_PwdContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_authnz_authz_authz_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq_PwdContent.ProtoReflect.Descriptor instead.
func (*LoginReq_PwdContent) Descriptor() ([]byte, []int) {
	return file_api_authnz_authz_authz_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoginReq_PwdContent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq_PwdContent) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

var File_api_authnz_authz_authz_proto protoreflect.FileDescriptor

var file_api_authnz_authz_authz_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x1a, 0x1b, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe9, 0x02, 0x0a, 0x08, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x74, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x58, 0x0a, 0x13, 0x73, 0x6d, 0x5f, 0x76, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x53, 0x6d, 0x56, 0x65,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x10,
	0x73, 0x6d, 0x56, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x44, 0x0a, 0x0b, 0x70, 0x77, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x7a, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x77,
	0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x77, 0x64, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x48, 0x0a, 0x10, 0x53, 0x6d, 0x56, 0x65, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x6d, 0x5f, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6d, 0x56, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x77, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x60, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x56, 0x65, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x56, 0x65, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x59, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x73,
	0x6d, 0x5f, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x6d, 0x56, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x09,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x0c, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2a, 0x57, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4d, 0x5f, 0x56, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x57, 0x44, 0x10, 0x02, 0x32, 0xb5, 0x02, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x7a,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e,
	0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x68, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x56, 0x65, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d,
	0x56, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x27, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x7a, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x56, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x46,
	0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x09, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x12, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e,
	0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x77, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3b, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x61,
	0x6f, 0x68, 0x75, 0x61, 0x73, 0x68, 0x69, 0x66, 0x75, 0x2f, 0x68, 0x69, 0x6d, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x7a, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_authnz_authz_authz_proto_rawDescOnce sync.Once
	file_api_authnz_authz_authz_proto_rawDescData = file_api_authnz_authz_authz_proto_rawDesc
)

func file_api_authnz_authz_authz_proto_rawDescGZIP() []byte {
	file_api_authnz_authz_authz_proto_rawDescOnce.Do(func() {
		file_api_authnz_authz_authz_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_authnz_authz_authz_proto_rawDescData)
	})
	return file_api_authnz_authz_authz_proto_rawDescData
}

var file_api_authnz_authz_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_authnz_authz_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_authnz_authz_authz_proto_goTypes = []interface{}{
	(LoginType)(0),                    // 0: authnz.authz.LoginType
	(*LoginReq)(nil),                  // 1: authnz.authz.LoginReq
	(*LoginResp)(nil),                 // 2: authnz.authz.LoginResp
	(*SendSmVerCodeForLoginReq)(nil),  // 3: authnz.authz.SendSmVerCodeForLoginReq
	(*SendSmVerCodeForLoginResp)(nil), // 4: authnz.authz.SendSmVerCodeForLoginResp
	(*UpdatePwdReq)(nil),              // 5: authnz.authz.UpdatePwdReq
	(*UpdatePwdResp)(nil),             // 6: authnz.authz.UpdatePwdResp
	(*LogoutReq)(nil),                 // 7: authnz.authz.LogoutReq
	(*LogoutResp)(nil),                // 8: authnz.authz.LogoutResp
	(*LoginReq_SmVerCodeContent)(nil), // 9: authnz.authz.LoginReq.SmVerCodeContent
	(*LoginReq_PwdContent)(nil),       // 10: authnz.authz.LoginReq.PwdContent
	(constant.Terminal)(0),            // 11: constant.Terminal
}
var file_api_authnz_authz_authz_proto_depIdxs = []int32{
	11, // 0: authnz.authz.LoginReq.terminal:type_name -> constant.Terminal
	9,  // 1: authnz.authz.LoginReq.sm_ver_code_content:type_name -> authnz.authz.LoginReq.SmVerCodeContent
	10, // 2: authnz.authz.LoginReq.pwd_content:type_name -> authnz.authz.LoginReq.PwdContent
	11, // 3: authnz.authz.SendSmVerCodeForLoginReq.terminal:type_name -> constant.Terminal
	1,  // 4: authnz.authz.AuthzService.Login:input_type -> authnz.authz.LoginReq
	3,  // 5: authnz.authz.AuthzService.SendSmVerCodeForLogin:input_type -> authnz.authz.SendSmVerCodeForLoginReq
	5,  // 6: authnz.authz.AuthzService.UpdatePwd:input_type -> authnz.authz.UpdatePwdReq
	7,  // 7: authnz.authz.AuthzService.Logout:input_type -> authnz.authz.LogoutReq
	2,  // 8: authnz.authz.AuthzService.Login:output_type -> authnz.authz.LoginResp
	4,  // 9: authnz.authz.AuthzService.SendSmVerCodeForLogin:output_type -> authnz.authz.SendSmVerCodeForLoginResp
	6,  // 10: authnz.authz.AuthzService.UpdatePwd:output_type -> authnz.authz.UpdatePwdResp
	8,  // 11: authnz.authz.AuthzService.Logout:output_type -> authnz.authz.LogoutResp
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_authnz_authz_authz_proto_init() }
func file_api_authnz_authz_authz_proto_init() {
	if File_api_authnz_authz_authz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_authnz_authz_authz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSmVerCodeForLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSmVerCodeForLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePwdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePwdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq_SmVerCodeContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authnz_authz_authz_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq_PwdContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_authnz_authz_authz_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LoginReq_SmVerCodeContent_)(nil),
		(*LoginReq_PwdContent_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_authnz_authz_authz_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_authnz_authz_authz_proto_goTypes,
		DependencyIndexes: file_api_authnz_authz_authz_proto_depIdxs,
		EnumInfos:         file_api_authnz_authz_authz_proto_enumTypes,
		MessageInfos:      file_api_authnz_authz_authz_proto_msgTypes,
	}.Build()
	File_api_authnz_authz_authz_proto = out.File
	file_api_authnz_authz_authz_proto_rawDesc = nil
	file_api_authnz_authz_authz_proto_goTypes = nil
	file_api_authnz_authz_authz_proto_depIdxs = nil
}
