// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: common/api/constant/constant.proto

package constant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 终端
type Terminal int32

const (
	Terminal_TerminalUnknown Terminal = 0 // 未知
	Terminal_TerminalApp     Terminal = 1 // App
	Terminal_TerminalPC      Terminal = 2 // PC
	Terminal_TerminalWeb     Terminal = 3 // Web
)

// Enum value maps for Terminal.
var (
	Terminal_name = map[int32]string{
		0: "TerminalUnknown",
		1: "TerminalApp",
		2: "TerminalPC",
		3: "TerminalWeb",
	}
	Terminal_value = map[string]int32{
		"TerminalUnknown": 0,
		"TerminalApp":     1,
		"TerminalPC":      2,
		"TerminalWeb":     3,
	}
)

func (x Terminal) Enum() *Terminal {
	p := new(Terminal)
	*p = x
	return p
}

func (x Terminal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Terminal) Descriptor() protoreflect.EnumDescriptor {
	return file_common_protocol_constant_constant_proto_enumTypes[0].Descriptor()
}

func (Terminal) Type() protoreflect.EnumType {
	return &file_common_protocol_constant_constant_proto_enumTypes[0]
}

func (x Terminal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Terminal.Descriptor instead.
func (Terminal) EnumDescriptor() ([]byte, []int) {
	return file_common_protocol_constant_constant_proto_rawDescGZIP(), []int{0}
}

// 性别
type Gender int32

const (
	Gender_GenderUnknown Gender = 0 // 未知
	Gender_GenderMale    Gender = 1 // 男性
	Gender_GenderFemale  Gender = 2 // 女性
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GenderUnknown",
		1: "GenderMale",
		2: "GenderFemale",
	}
	Gender_value = map[string]int32{
		"GenderUnknown": 0,
		"GenderMale":    1,
		"GenderFemale":  2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_protocol_constant_constant_proto_enumTypes[1].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_protocol_constant_constant_proto_enumTypes[1]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_protocol_constant_constant_proto_rawDescGZIP(), []int{1}
}

var File_common_protocol_constant_constant_proto protoreflect.FileDescriptor

var file_common_protocol_constant_constant_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x2a, 0x51, 0x0a, 0x08, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12,
	0x13, 0x0a, 0x0f, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c,
	0x41, 0x70, 0x70, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x50, 0x43, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x57, 0x65, 0x62, 0x10, 0x03, 0x2a, 0x3d, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x11, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x6c,
	0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x46, 0x65, 0x6d,
	0x61, 0x6c, 0x65, 0x10, 0x02, 0x42, 0x1e, 0x5a, 0x1c, 0x68, 0x69, 0x6d, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_protocol_constant_constant_proto_rawDescOnce sync.Once
	file_common_protocol_constant_constant_proto_rawDescData = file_common_protocol_constant_constant_proto_rawDesc
)

func file_common_protocol_constant_constant_proto_rawDescGZIP() []byte {
	file_common_protocol_constant_constant_proto_rawDescOnce.Do(func() {
		file_common_protocol_constant_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_protocol_constant_constant_proto_rawDescData)
	})
	return file_common_protocol_constant_constant_proto_rawDescData
}

var file_common_protocol_constant_constant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_protocol_constant_constant_proto_goTypes = []interface{}{
	(Terminal)(0), // 0: constant.Terminal
	(Gender)(0),   // 1: constant.Gender
}
var file_common_protocol_constant_constant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_protocol_constant_constant_proto_init() }
func file_common_protocol_constant_constant_proto_init() {
	if File_common_protocol_constant_constant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_protocol_constant_constant_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_protocol_constant_constant_proto_goTypes,
		DependencyIndexes: file_common_protocol_constant_constant_proto_depIdxs,
		EnumInfos:         file_common_protocol_constant_constant_proto_enumTypes,
	}.Build()
	File_common_protocol_constant_constant_proto = out.File
	file_common_protocol_constant_constant_proto_rawDesc = nil
	file_common_protocol_constant_constant_proto_goTypes = nil
	file_common_protocol_constant_constant_proto_depIdxs = nil
}
